"""Shared model USLSIG2 TypeGraph framing/canonicalisation, not a host parser.
MS.canonical: ms_blob/ms_len -> ms_canon/ms_canonlen, name/nameid, count,
variadic/mode/support and resultkind/resultwidth. All scratch uses ms_.
Input/output restored; SB scratch unspecified. Recursive base/shape become zero.
"""
LIMIT, END, KIND, WIDTH, TAG, COUNT, INDEX, ALIGN = (i<<40 for i in range(350,358))
# Separate banks from existing descriptor 350..357 and variadic 400..407.
DEPTH, SIGCOUNT, SIGINDEX, SIGCALLBASE = (i<<40 for i in range(410,414))
assert not set(range(410,414)) & (set(range(350,358)) | set(range(400,408)))
def install(E,fail='DEAD'):
 P=E.P
 if 'MS.canonical' in E.g.st:return
 def eq(n,x,v,y,z):P(n).branch({1:y},z,[('LDI','ms_eq',v),('C64U',x,'ms_eq')])
 def maxv(n,x,v,nx):P(n).branch({2:'MS.fail'},nx,[('LDI','ms_max',v),('C64U',x,'ms_max')])
 def get(p,x,b):return p.a(('LDX',x,'ms_level',b))
 def put(p,x,b):return p.a(('STX','ms_level',b,x))
 P('MS.fail').a(E.rej('not covered: typed library signature')).goto(fail)
 P('MS.return').ret()
 from modelinput import u64
 u64(E,'MS.callablecap',b'\0library/callables','ms_callablecap','ms_callablepresent','MS.fail')
 P('MS.canonical').call('MS.callablecap').a(('INPUSH','ms_blob'),('COPYW','ms_limit','ms_len'),('OLEN','ms_cut'),('LDI','ms_level',0),('LDI','ms_nodes',0),('LDI','ms_signatures',0),('LDI','ms_callbacks',0),('LDI','ms_zero',0)).goto('MS.extent')
 maxv('MS.extent','ms_len',16777216,'MS.magic0')
 for i,c in enumerate(b'USLSIG2\n'):
  P('MS.magic'+str(i)).call('MS.byte').branch({c:'MS.magic'+str(i+1) if i<7 else 'MS.records'},'MS.fail',[('RLD','ms_byte')])
 P('MS.records').call('MS.u64').branch({1:'MS.namelen'},'MS.fail',[('LDI','ms_one',1),('C64U','ms_value','ms_one')])
 P('MS.namelen').call('MS.u64').a(('COPYW','ms_n','ms_value'),('LDI','ms_i',0),('MARK','ms_ns')).goto('MS.namebound')
 maxv('MS.namebound','ms_n',1024,'MS.nameempty')
 eq('MS.nameempty','ms_n',0,'MS.fail','MS.name')
 P('MS.name').branch({1:'MS.named'},'MS.namebyte',[('CMP','ms_i','ms_n')])
 P('MS.namebyte').call('MS.byte').branch({tuple(b'_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'):'MS.nameadv'},'MS.namedigit',[('RLD','ms_byte')])
 eq('MS.namedigit','ms_i',0,'MS.fail','MS.namedigit2')
 P('MS.namedigit2').branch({tuple(range(48,58)):'MS.nameadv'},'MS.fail',[('RLD','ms_byte')])
 P('MS.nameadv').a(('ALUI','add','ms_i','ms_i',1)).goto('MS.name')
 P('MS.named').a(('MARK','ms_ne'),('INTERN','ms_nameid','ms_ns','ms_ne'),('OLEN','ms_namecut'),('SPAN2','ms_ns','ms_ne'),('OCUT','ms_name','ms_namecut')).call('MS.byte').branch({0:'MS.defined'},'MS.fail',[('RLD','ms_byte')])
 P('MS.defined').call('MS.byte').branch({1:'MS.var'},'MS.fail',[('RLD','ms_byte')])
 P('MS.var').call('MS.bit').a(('COPYW','ms_variadic','ms_byte'),('OUTW','ms_byte')).call('MS.bit').a(('COPYW','ms_mode','ms_byte')).call('MS.u64').a(('COPYW','ms_count','ms_value')).call('MS.write64').goto('MS.countbound')
 maxv('MS.countbound','ms_count',1024,'MS.modevar')
 eq('MS.modevar','ms_variadic',1,'MS.stack','MS.modecount')
 P('MS.modecount').branch({2:'MS.stack'},'MS.register',[('LDI','ms_max',6),('C64U','ms_count','ms_max')])
 eq('MS.stack','ms_mode',1,'MS.result','MS.fail');eq('MS.register','ms_mode',0,'MS.result','MS.fail')
 P('MS.result').call('MS.desc').a(('COPYW','ms_resultkind','ms_lastkind'),('COPYW','ms_resultwidth','ms_lastwidth')).call('MS.u64').branch({1:'MS.paramsstart'},'MS.fail',[('C64U','ms_value','ms_count')])
 P('MS.paramsstart').a(('LDI','ms_pi',0)).goto('MS.params')
 P('MS.params').branch({1:'MS.support'},'MS.param',[('CMP','ms_pi','ms_count')])
 P('MS.param').call('MS.desc').a(('ALUI','add','ms_pi','ms_pi',1)).goto('MS.params')
 P('MS.support').call('MS.bit').a(('COPYW','ms_support','ms_byte')).goto('MS.supportgraph')
 eq('MS.supportgraph','ms_callbacks',0,'MS.supportend','MS.supportzero')
 eq('MS.supportzero','ms_callablecap',1,'MS.supportend','MS.supportlegacyzero')
 eq('MS.supportlegacyzero','ms_support',0,'MS.supportend','MS.fail')
 P('MS.supportend').a(('MARK','ms_pos')).branch({1:'MS.done'},'MS.fail',[('C64U','ms_pos','ms_len')])
 P('MS.done').a(('OCUT','ms_canon','ms_cut'),('BLEN','ms_canonlen','ms_canon'),('INPOP',)).ret()
 P('MS.desc').a(('ALUI','add','ms_level','ms_level',1),('ALUI','add','ms_nodes','ms_nodes',1)).goto('MS.depth')
 maxv('MS.depth','ms_level',32,'MS.nodebound');maxv('MS.nodebound','ms_nodes',16384,'MS.fields0')
 for i in range(7):
  p=P('MS.fields'+str(i))
  if i==0:put(p,'ms_limit',LIMIT)
  p.call('MS.u64')
  if i==0:put(p,'ms_value',DEPTH)
  if i in (1,2):p.a(('LDI','ms_value',0))
  if i==3:put(p,'ms_value',KIND)
  if i==4:put(p,'ms_value',WIDTH)
  if i==5:p.a(('COPYW','ms_unsigned','ms_value'))
  if i==6:put(p,'ms_value',ALIGN)
  p.call('MS.write64').goto('MS.fields'+str(i+1) if i<6 else 'MS.kindbound')
 get(P('MS.kindbound'),'ms_kind',KIND).goto('MS.kindmax')
 maxv('MS.kindmax','ms_kind',6,'MS.unsbound')
 maxv('MS.unsbound','ms_unsigned',1,'MS.width')
 get(P('MS.width'),'ms_width',WIDTH).branch({(0,6):'MS.widthzero',1:'MS.widthint',(2,4):'MS.widthptr',3:'MS.widthfp',5:'MS.widthagg'},'MS.fail',[('RLD','ms_kind')])
 eq('MS.widthzero','ms_width',0,'MS.align','MS.fail')
 maxv('MS.widthint','ms_width',8,'MS.widthintkeys')
 P('MS.widthintkeys').branch({(1,2,4,8):'MS.align'},'MS.fail',[('RLD','ms_width')])
 eq('MS.widthptr','ms_width',8,'MS.align','MS.fail')
 maxv('MS.widthfp','ms_width',8,'MS.widthfpkeys')
 P('MS.widthfpkeys').branch({(4,8):'MS.align'},'MS.fail',[('RLD','ms_width')])
 eq('MS.widthagg','ms_width',0,'MS.fail','MS.widthmax');maxv('MS.widthmax','ms_width',16777216,'MS.align')
 get(P('MS.align'),'ms_align',ALIGN).branch({(0,6):'MS.alignzero'},'MS.alignnonzero',[('RLD','ms_kind')])
 eq('MS.alignzero','ms_align',0,'MS.tag','MS.fail');eq('MS.alignnonzero','ms_align',0,'MS.fail','MS.alignmax')
 maxv('MS.alignmax','ms_align',65536,'MS.alignpow')
 P('MS.alignpow').a(('A64I','sub','ms_tmp','ms_align',1),('A64','and','ms_tmp','ms_tmp','ms_align')).branch({1:'MS.tag'},'MS.fail',[('CMPI','ms_tmp',0)])
 put(P('MS.tag').call('MS.byte').a(('COPYW','ms_tag','ms_byte'),('OUTW','ms_byte')),'ms_tag',TAG).call('MS.u64').a(('COPYW','ms_payload','ms_value')).call('MS.write64').a(('MARK','ms_pos'),('A64','sub','ms_left','ms_limit','ms_pos')).branch({2:'MS.fail'},'MS.payloadmax',[('C64U','ms_payload','ms_left')])
 maxv('MS.payloadmax','ms_payload',16777216,'MS.payloadend')
 put(P('MS.payloadend').a(('A64','add','ms_limit','ms_pos','ms_payload')),'ms_limit',END).branch({5:'MS.aggregate',4:'MS.function'},'MS.primitive',[('RLD','ms_kind')])
 eq('MS.primitive','ms_tag',0,'MS.empty','MS.fail')
 P('MS.function').a(('ALUI','add','ms_callbacks','ms_callbacks',1)).branch({0:'MS.empty',4:'MS.functionpayload'},'MS.fail',[('RLD','ms_tag')])
 eq('MS.functionpayload','ms_payload',0,'MS.descdone','MS.functiondepth')
 get(P('MS.functiondepth'),'ms_depth',DEPTH).goto('MS.functiondepthcheck')
 eq('MS.functiondepthcheck','ms_depth',1,'MS.functionalign','MS.fail')
 get(P('MS.functionalign'),'ms_align',ALIGN).goto('MS.functionaligncheck')
 eq('MS.functionaligncheck','ms_align',8,'MS.sigschema','MS.fail')
 P('MS.sigschema').call('MS.byte').branch({1:'MS.sigform'},'MS.fail',[('RLD','ms_byte')])
 P('MS.sigform').a(('OUTW','ms_byte')).call('MS.byte').a(('COPYW','ms_form','ms_byte'),('OUTW','ms_byte')).branch({0:'MS.sigdef',1:'MS.sigref'},'MS.fail',[('RLD','ms_form')])
 P('MS.sigref').call('MS.u64').goto('MS.sigrefzero')
 eq('MS.sigrefzero','ms_value',0,'MS.fail','MS.sigrefbound')
 P('MS.sigrefbound').branch({2:'MS.fail'},'MS.sigrefwrite',[('C64U','ms_value','ms_signatures')])
 P('MS.sigrefwrite').call('MS.write64').goto('MS.descdone')
 P('MS.sigdef').call('MS.u64').a(('ALUI','add','ms_signatures','ms_signatures',1)).branch({1:'MS.sigdefbound'},'MS.fail',[('C64U','ms_value','ms_signatures')])
 maxv('MS.sigdefbound','ms_signatures',1024,'MS.sigdefwrite')
 # Register before child parsing, permitting self and mutually recursive edges.
 P('MS.sigdefwrite').a(('COPYW','ms_value','ms_signatures')).call('MS.write64').call('MS.bit').a(('COPYW','ms_sigvar','ms_byte'),('OUTW','ms_byte')).call('MS.bit').a(('COPYW','ms_sigmode','ms_byte'),('OUTW','ms_byte')).call('MS.u64').call('MS.write64').goto('MS.sigcountbound')
 maxv('MS.sigcountbound','ms_value',1024,'MS.sigcountsave')
 put(put(P('MS.sigcountsave'),'ms_value',SIGCOUNT),'ms_callbacks',SIGCALLBASE).a(('COPYW','ms_sigcount','ms_value')).goto('MS.sigmodevar')
 eq('MS.sigmodevar','ms_sigvar',1,'MS.sigstack','MS.sigmodecount')
 P('MS.sigmodecount').branch({2:'MS.sigstack'},'MS.sigregister',[('LDI','ms_max',6),('C64U','ms_sigcount','ms_max')])
 eq('MS.sigstack','ms_sigmode',1,'MS.sigresult','MS.fail')
 eq('MS.sigregister','ms_sigmode',0,'MS.sigresult','MS.fail')
 get(P('MS.sigresult').call('MS.desc').call('MS.u64'),'ms_sigcount',SIGCOUNT).branch({1:'MS.sigparamsstart'},'MS.fail',[('C64U','ms_value','ms_sigcount')])
 put(P('MS.sigparamsstart').call('MS.write64').a(('LDI','ms_si',0)),'ms_si',SIGINDEX).goto('MS.sigparams')
 get(get(P('MS.sigparams'),'ms_si',SIGINDEX),'ms_sigcount',SIGCOUNT).branch({1:'MS.sigsupport'},'MS.sigparam',[('CMP','ms_si','ms_sigcount')])
 P('MS.sigparam').call('MS.desc').goto('MS.signext')
 put(get(P('MS.signext'),'ms_si',SIGINDEX).a(('ALUI','add','ms_si','ms_si',1)),'ms_si',SIGINDEX).goto('MS.sigparams')
 get(P('MS.sigsupport').call('MS.bit').a(('COPYW','ms_sigsupport','ms_byte')),'ms_callbase',SIGCALLBASE).branch({1:'MS.sigsupportwrite'},'MS.sigsupportzero',[('C64U','ms_callbase','ms_callbacks')])
 eq('MS.sigsupportzero','ms_callablecap',1,'MS.sigsupportwrite','MS.sigsupportlegacyzero')
 eq('MS.sigsupportlegacyzero','ms_sigsupport',0,'MS.sigsupportwrite','MS.fail')
 P('MS.sigsupportwrite').a(('OUTW','ms_sigsupport')).goto('MS.descdone')
 eq('MS.empty','ms_payload',0,'MS.descdone','MS.fail')
 P('MS.aggregate').branch({(1,2):'MS.members',3:'MS.array'},'MS.fail',[('RLD','ms_tag')])
 put(P('MS.members').call('MS.u64').call('MS.write64'),'ms_value',COUNT).goto('MS.membermax')
 maxv('MS.membermax','ms_value',64,'MS.memberstart')
 put(P('MS.memberstart').a(('LDI','ms_mi',0)),'ms_mi',INDEX).goto('MS.memberloop')
 get(get(P('MS.memberloop'),'ms_mi',INDEX),'ms_mc',COUNT).branch({1:'MS.descdone'},'MS.member0',[('CMP','ms_mi','ms_mc')])
 for i in range(4):P('MS.member'+str(i)).call('MS.u64').call('MS.write64').goto('MS.member'+str(i+1) if i<3 else 'MS.child')
 P('MS.child').call('MS.desc').goto('MS.membernext')
 put(get(P('MS.membernext'),'ms_mi',INDEX).a(('ALUI','add','ms_mi','ms_mi',1)),'ms_mi',INDEX).goto('MS.memberloop')
 P('MS.array').call('MS.u64').a(('COPYW','ms_arraycount','ms_value')).call('MS.write64').goto('MS.arraycountmax')
 maxv('MS.arraycountmax','ms_arraycount',16777216,'MS.arraystride')
 P('MS.arraystride').call('MS.u64').a(('COPYW','ms_stride','ms_value')).call('MS.write64').goto('MS.arraystridemax')
 maxv('MS.arraystridemax','ms_stride',16777216,'MS.arraysize')
 get(P('MS.arraysize').a(('A64','mul','ms_tmp','ms_arraycount','ms_stride')),'ms_width',WIDTH).branch({1:'MS.arraychild'},'MS.fail',[('C64U','ms_tmp','ms_width')])
 P('MS.arraychild').call('MS.desc').goto('MS.descdone')
 get(P('MS.descdone').a(('MARK','ms_pos')),'ms_end',END).branch({1:'MS.descreturn'},'MS.fail',[('C64U','ms_pos','ms_end')])
 get(get(get(P('MS.descreturn'),'ms_limit',LIMIT),'ms_lastkind',KIND),'ms_lastwidth',WIDTH).a(('ALUI','sub','ms_level','ms_level',1)).ret()
 P('MS.bit').call('MS.byte').branch({(0,1):'MS.return'},'MS.fail',[('RLD','ms_byte')])
 P('MS.byte').a(('MARK','ms_pos')).branch({0:'MS.byteok'},'MS.fail',[('C64U','ms_pos','ms_limit')])
 P('MS.byteok').a(('BYTE','ms_byte'),('ADV',)).ret()
 P('MS.u64').a(('LDI','ms_value',0),('LDI','ms_shift',0)).goto('MS.u64loop')
 P('MS.u64loop').call('MS.byte').a(('A64','shl','ms_part','ms_byte','ms_shift'),('A64','or','ms_value','ms_value','ms_part'),('ALUI','add','ms_shift','ms_shift',8)).branch({1:'MS.return'},'MS.u64loop',[('CMPI','ms_shift',64)])
 P('MS.write64').a(('LDI','ms_shift',0)).goto('MS.writeloop')
 P('MS.writeloop').a(('A64','shr','ms_part','ms_value','ms_shift'),('OUTW','ms_part'),('ALUI','add','ms_shift','ms_shift',8)).branch({1:'MS.return'},'MS.writeloop',[('CMPI','ms_shift',64)])
