"""USBIND2 candidate selection in delta, normalized to the existing USBIND1 decoder.
Winner priority is (origin, ordinal), independent of record order. Output names
retain first-seen order; no host parser or host winner selection participates.
V1 passthrough does not alter the caller's input/output/string builder.
"""
LIST, SEEN, DUP, RANK, BEGIN, END, ORIGIN, LENGTH = (i<<40 for i in range(300,308))

def install(E, fail='DEAD'):
    P=E.P
    if 'MC.normalize' in E.g.st: return
    from modelsignature import install as install_signature
    install_signature(E,fail)
    def eq(n,a,b,yes,no): P(n).branch({1:yes},no,[('C64U',a,b)])
    def maximum(n,a,v,nx): P(n).branch({2:'MC.fail'},nx,[('LDI','mc_max',v),('C64U',a,'mc_max')])
    P('MC.fail').a(E.rej('not covered: library candidate wire')).goto(fail)
    P('MC.normalize').a(('INPUSH','mc_blob'),('COPYW','mc_limit','mc_len')).goto('MC.magic0')
    for i,c in enumerate(b'USBIND'):
        P('MC.magic'+str(i)).call('MC.byte').branch({c:'MC.magic'+str(i+1)},'MC.fail',[('RLD','mc_byte')])
    P('MC.magic6').call('MC.byte').branch({49:'MC.v1',50:'MC.v2',51:'MC.v3'},'MC.fail',[('RLD','mc_byte')])
    P('MC.v1').a(('LDI','mc_version',1)).goto('MC.v2newline')
    P('MC.v2').a(('LDI','mc_version',2)).goto('MC.v2newline')
    P('MC.v3').a(('LDI','mc_version',3)).goto('MC.v2newline')
    P('MC.v2newline').call('MC.byte').branch({10:'MC.count'},'MC.fail',[('RLD','mc_byte')])
    P('MC.count').call('MC.u64').a(('COPYW','mc_count','mc_value'),('LDI','mc_i',0),('LDI','mc_unique',0)).goto('MC.countmax')
    maximum('MC.countmax','mc_count',65536,'MC.record')
    eq('MC.record','mc_i','mc_count','MC.inputend','MC.length')
    P('MC.length').a(('COPYW','mc_limit','mc_len')).call('MC.u64').a(('COPYW','mc_recordlen','mc_value'),('MARK','mc_begin'),('A64','add','mc_end','mc_begin','mc_value')).branch({0:'MC.fail',1:'MC.fail'},'MC.endmax',[('C64U','mc_end','mc_begin')])
    P('MC.endmax').branch({2:'MC.fail'},'MC.namelen',[('C64U','mc_end','mc_len')])
    P('MC.namelen').a(('COPYW','mc_limit','mc_end')).call('MC.u64').a(('COPYW','mc_n','mc_value'),('LDI','mc_j',0),('MARK','mc_nstart')).branch({1:'MC.fail'},'MC.namemax',[('LDI','mc_zero',0),('C64U','mc_n','mc_zero')])
    maximum('MC.namemax','mc_n',1024,'MC.name')
    eq('MC.name','mc_j','mc_n','MC.named','MC.namebyte')
    P('MC.namebyte').call('MC.byte').branch({x:'MC.nameok' for x in b'_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'},'MC.digitfirst',[('RLD','mc_byte')])
    P('MC.digitfirst').branch({1:'MC.fail'},'MC.digit',[('CMPI','mc_j',0)])
    P('MC.digit').branch({x:'MC.nameok' for x in range(48,58)},'MC.fail',[('RLD','mc_byte')])
    P('MC.nameok').a(('ALUI','add','mc_j','mc_j',1)).goto('MC.name')
    P('MC.named').a(('MARK','mc_nend'),('INTERN','mc_id','mc_nstart','mc_nend')).call('MC.byte').a(('COPYW','mc_kind','mc_byte')).branch({0:'MC.origin',1:'MC.origin'},'MC.fail',[('RLD','mc_byte')])
    P('MC.origin').a(('MARK','mc_originpos')).call('MC.byte').a(('COPYW','mc_origin','mc_byte')).branch({0:'MC.versionordinal',1:'MC.versionordinal',2:'MC.versionordinal'},'MC.fail',[('RLD','mc_byte')])
    P('MC.versionordinal').branch({1:'MC.v1origin'},'MC.ordinal',[('CMPI','mc_version',1)])
    P('MC.v1origin').a(('LDI','mc_ord',0)).branch({0:'MC.rankfixed'},'MC.fail',[('RLD','mc_origin')])
    P('MC.ordinal').call('MC.u64').a(('COPYW','mc_ord','mc_value')).branch({1:'MC.owned'},'MC.fixed',[('CMPI','mc_origin',2)])
    P('MC.fixed').branch({1:'MC.rankfixed'},'MC.fail',[('LDI','mc_zero',0),('C64U','mc_ord','mc_zero')])
    P('MC.rankfixed').a(('COPYW','mc_rank','mc_origin')).goto('MC.abi')
    P('MC.owned').branch({1:'MC.fail'},'MC.ownedmax',[('LDI','mc_zero',0),('C64U','mc_ord','mc_zero')])
    maximum('MC.ownedmax','mc_ord',64,'MC.rankowned')
    P('MC.rankowned').a(('A64I','add','mc_rank','mc_ord',2)).goto('MC.abi')
    P('MC.abi').call('MC.byte').branch({0:'MC.var'},'MC.fail',[('RLD','mc_byte')])
    P('MC.var').call('MC.byte').a(('COPYW','mc_variadic','mc_byte')).branch({0:'MC.address',1:'MC.address'},'MC.fail',[('RLD','mc_byte')])
    P('MC.address').call('MC.u64').a(('COPYW','mc_address','mc_value')).branch({1:'MC.fail'},'MC.addressmax',[('LDI','mc_zero',0),('C64U','mc_value','mc_zero')])
    maximum('MC.addressmax','mc_address',9223372036854775807,'MC.argc')
    P('MC.argc').call('MC.u64').a(('COPYW','mc_argc','mc_value')).goto('MC.argmax')
    maximum('MC.argmax','mc_argc',1024,'MC.formatversion')
    P('MC.formatversion').branch({1:'MC.format'},'MC.argkind',[('CMPI','mc_version',3)])
    P('MC.format').call('MC.byte').a(('COPYW','mc_format','mc_byte')).branch({0:'MC.argkind',1:'MC.typedkind',2:'MC.typedkind'},'MC.fail',[('RLD','mc_byte')])
    P('MC.typedkind').branch({1:'MC.typeddispatcher'},'MC.fail',[('CMPI','mc_kind',0)])
    P('MC.typeddispatcher').call('MC.u64').branch({1:'MC.fail'},'MC.typedplan',[('C64U','mc_value','mc_zero')])
    P('MC.typedplan').call('MC.u64').a(('COPYW','mc_plan','mc_value')).call('MC.u64').a(('COPYW','ms_len','mc_value'),('MARK','mc_sigstart'),('A64','sub','mc_left','mc_end','mc_sigstart')).branch({2:'MC.fail'},'MC.typedblob',[('C64U','ms_len','mc_left')])
    P('MC.typedblob').a(('A64','add','mc_sigend','mc_sigstart','ms_len'),('OLEN','mc_sigcut'),('SPAN2','mc_sigstart','mc_sigend'),('OCUT','ms_blob','mc_sigcut'),('JUMP','mc_sigend')).call('MS.canonical').branch({1:'MC.typedcount'},'MC.fail',[('CMP','mc_id','ms_nameid')])
    P('MC.typedcount').branch({1:'MC.typedvar'},'MC.fail',[('C64U','mc_argc','ms_count')])
    P('MC.typedvar').branch({1:'MC.typedformat'},'MC.fail',[('CMP','mc_variadic','ms_variadic')])
    P('MC.typedformat').branch({2:'MC.templatevar'},'MC.typedsupported',[('RLD','mc_format')])
    P('MC.templatevar').branch({1:'MC.templateprefix'},'MC.fail',[('CMPI','ms_variadic',1)])
    P('MC.templateprefix').branch({1:'MC.fail'},'MC.templatemode',[('C64U','ms_count','mc_zero')])
    P('MC.templatemode').branch({1:'MC.templatesupport'},'MC.fail',[('CMPI','ms_mode',1)])
    # Prototype support is deliberately 0: no concrete variadic cif exists yet.
    P('MC.templatesupport').branch({1:'MC.typedsupported'},'MC.fail',[('CMPI','ms_support',0)])
    P('MC.typedsupported').call('MC.byte').branch({0:'MC.bound',1:'MC.typedhasplan'},'MC.fail',[('RLD','mc_byte')])
    P('MC.typedhasplan').branch({1:'MC.fail'},'MC.typedissupported',[('C64U','mc_plan','mc_zero')])
    P('MC.typedissupported').branch({2:'MC.bound'},'MC.typedfixedsupported',[('RLD','mc_format')])
    from modelinput import u64
    u64(E,'MC.callablecap',b'\0library/callables','mc_callablecap','mc_callablepresent','MC.fail')
    P('MC.typedfixedsupported').branch({1:'MC.bound'},'MC.typedcallablecap',[('CMPI','ms_support',1)])
    P('MC.typedcallablecap').call('MC.callablecap').branch({1:'MC.bound'},'MC.fail',[('CMPI','mc_callablecap',1)])
    P('MC.argkind').branch({1:'MC.dataargc'},'MC.descinit',[('CMPI','mc_kind',1)])
    eq('MC.dataargc','mc_argc','mc_zero','MC.datavar','MC.fail')
    eq('MC.datavar','mc_variadic','mc_zero','MC.descinit','MC.fail')
    P('MC.descinit').a(('LDI','mc_d',0)).goto('MC.desc')
    # Structural facts only. Opaque aggregate/unknown descriptors remain legal
    # candidates; the selected record's existing typed decoder proves support.
    for f in range(6):
        P('MC.desc' if f==0 else 'MC.desc'+str(f)).call('MC.u64').a(('COPYW','mc_f'+str(f),'mc_value')).goto('MC.desc'+str(f+1))
    P('MC.desc6').goto('MC.classmax')
    maximum('MC.classmax','mc_f3',6,'MC.unsmax')
    maximum('MC.unsmax','mc_f5',1,'MC.desctype')
    P('MC.desctype').branch({0:'MC.void',1:'MC.integer',2:'MC.pointer',3:'MC.float',4:'MC.pointer'},'MC.descnext',[('RLD','mc_f3')])
    P('MC.void').branch({1:'MC.voidkind'},'MC.fail',[('CMPI','mc_d',0)])
    P('MC.voidkind').branch({1:'MC.voidfacts'},'MC.fail',[('CMPI','mc_kind',0)])
    P('MC.voidfacts').a(('A64','or','mc_test','mc_f0','mc_f4'),('A64','or','mc_test','mc_test','mc_f5')).branch({1:'MC.descnext'},'MC.fail',[('C64U','mc_test','mc_zero')])
    P('MC.integer').branch({1:'MC.intwidthmax'},'MC.fail',[('C64U','mc_f0','mc_zero')])
    maximum('MC.intwidthmax','mc_f4',8,'MC.intwidth')
    P('MC.intwidth').branch({1:'MC.descnext',2:'MC.descnext',4:'MC.descnext',8:'MC.descnext'},'MC.fail',[('RLD','mc_f4')])
    P('MC.pointer').branch({1:'MC.fail'},'MC.ptrwidth',[('C64U','mc_f0','mc_zero')])
    P('MC.ptrwidth').branch({1:'MC.ptruns'},'MC.fail',[('LDI','mc_eight',8),('C64U','mc_f4','mc_eight')])
    eq('MC.ptruns','mc_f5','mc_zero','MC.descnext','MC.fail')
    P('MC.float').a(('A64','or','mc_test','mc_f0','mc_f5')).branch({1:'MC.floatwidthmax'},'MC.fail',[('C64U','mc_test','mc_zero')])
    maximum('MC.floatwidthmax','mc_f4',8,'MC.floatwidth')
    P('MC.floatwidth').branch({4:'MC.descnext',8:'MC.descnext'},'MC.fail',[('RLD','mc_f4')])
    P('MC.descnext').a(('ALUI','add','mc_d','mc_d',1)).branch({2:'MC.tail'},'MC.desc',[('C64U','mc_d','mc_argc')])
    P('MC.tail').branch({1:'MC.extent'},'MC.supported',[('CMPI','mc_kind',1)])
    P('MC.extent').call('MC.u64').branch({1:'MC.fail'},'MC.extentwidth',[('C64U','mc_value','mc_zero')])
    P('MC.extentwidth').branch({0:'MC.fail'},'MC.extentadd',[('C64U','mc_value','mc_f4')])
    P('MC.extentadd').a(('A64','add','mc_extentend','mc_address','mc_value')).branch({0:'MC.fail',1:'MC.fail'},'MC.writable',[('C64U','mc_extentend','mc_address')])
    P('MC.writable').call('MC.byte').branch({0:'MC.supported',1:'MC.supported'},'MC.fail',[('RLD','mc_byte')])
    P('MC.supported').call('MC.byte').branch({0:'MC.bound',1:'MC.bound'},'MC.fail',[('RLD','mc_byte')])
    P('MC.bound').a(('MARK','mc_pos')).branch({1:'MC.duplicate'},'MC.fail',[('C64U','mc_pos','mc_end')])
    P('MC.duplicate').a(('A64I','mul','mc_key','mc_id',67),('A64','add','mc_key','mc_key','mc_rank'),('LDX','mc_seen','mc_key',DUP)).branch({1:'MC.dupnew'},'MC.fail',[('CMPI','mc_seen',0)])
    P('MC.dupnew').a(('LDI','mc_one',1),('STX','mc_key',DUP,'mc_one'),('LDX','mc_seen','mc_id',SEEN)).branch({1:'MC.new'},'MC.old',[('CMPI','mc_seen',0)])
    P('MC.new').branch({2:'MC.fail',1:'MC.fail'},'MC.newput',[('LDI','mc_max',1024),('C64U','mc_unique','mc_max')])
    P('MC.newput').a(('STX','mc_id',SEEN,'mc_one'),('STX','mc_unique',LIST,'mc_id'),('ALUI','add','mc_unique','mc_unique',1)).goto('MC.choose')
    P('MC.old').a(('LDX','mc_best','mc_id',RANK)).branch({0:'MC.choose'},'MC.next',[('C64U','mc_rank','mc_best')])
    P('MC.choose').a(*[('STX','mc_id',bank,reg) for bank,reg in [(RANK,'mc_rank'),(BEGIN,'mc_begin'),(END,'mc_end'),(ORIGIN,'mc_originpos'),(LENGTH,'mc_recordlen')]]).goto('MC.next')
    P('MC.next').a(('ALUI','add','mc_i','mc_i',1)).goto('MC.record')
    P('MC.inputend').a(('MARK','mc_pos')).branch({1:'MC.endversion'},'MC.fail',[('C64U','mc_pos','mc_len')])
    P('MC.endversion').branch({1:'MC.v1done'},'MC.output',[('CMPI','mc_version',1)])
    P('MC.v1done').a(('INPOP',)).ret()
    P('MC.output').a(('OLEN','mc_cut'),*[('OUT',c) for c in b'USBIND']).branch({1:'MC.output3'},'MC.output1',[('CMPI','mc_version',3)])
    P('MC.output3').a(('OUT',51),('OUT',10)).goto('MC.outputcount')
    P('MC.output1').a(('OUT',49),('OUT',10)).goto('MC.outputcount')
    P('MC.outputcount').a(('COPYW','mc_value','mc_unique')).call('MC.write64').a(('LDI','mc_i',0)).goto('MC.emit')
    eq('MC.emit','mc_i','mc_unique','MC.done','MC.emitrecord')
    P('MC.emitrecord').a(('LDX','mc_id','mc_i',LIST),*[('LDX',reg,'mc_id',bank) for bank,reg in [(BEGIN,'mc_begin'),(END,'mc_end'),(ORIGIN,'mc_originpos'),(LENGTH,'mc_recordlen')]]).branch({1:'MC.emit3'},'MC.emit1',[('CMPI','mc_version',3)])
    P('MC.emit1').a(('A64I','sub','mc_value','mc_recordlen',8)).call('MC.write64').a(('SPAN2','mc_begin','mc_originpos'),('OUT',0)).goto('MC.emittail')
    P('MC.emit3').a(('COPYW','mc_value','mc_recordlen')).call('MC.write64').a(('SPAN2','mc_begin','mc_originpos'),*[('OUT',0) for _ in range(9)]).goto('MC.emittail')
    P('MC.emittail').a(('A64I','add','mc_tail','mc_originpos',9),('SPAN2','mc_tail','mc_end'),('ALUI','add','mc_i','mc_i',1)).goto('MC.emit')
    P('MC.done').a(('OCUT','mc_blob','mc_cut'),('BLEN','mc_len','mc_blob'),('INPOP',)).ret()
    P('MC.byte').a(('MARK','mc_pos')).branch({0:'MC.byteok'},'MC.fail',[('C64U','mc_pos','mc_limit')])
    P('MC.byteok').a(('BYTE','mc_byte'),('ADV',)).ret()
    P('MC.u64').a(('LDI','mc_value',0),('LDI','mc_shift',0)).goto('MC.u64loop')
    P('MC.u64loop').call('MC.byte').a(('A64','shl','mc_part','mc_byte','mc_shift'),('A64','or','mc_value','mc_value','mc_part'),('ALUI','add','mc_shift','mc_shift',8)).branch({1:'RET'},'MC.u64loop',[('CMPI','mc_shift',64)])
    P('MC.write64').a(('LDI','mc_shift',0)).goto('MC.writeloop')
    P('MC.writeloop').a(('A64','shr','mc_part','mc_value','mc_shift'),('OUTW','mc_part'),('ALUI','add','mc_shift','mc_shift',8)).branch({1:'RET'},'MC.writeloop',[('CMPI','mc_shift',64)])
