"""Bounded semantic USLSIG2 graph equality in ordinary model actions.
MG.equal: mg_left_blob/mg_left_len, mg_right_blob/mg_right_len -> mg_equal.
Canonical validation precedes indexing. Top-level mode is excluded by the old
contract; nested modes and every ABI layout fact remain significant. No host
parser, graph isomorphism or callback execution. Budget exhaustion rejects.
"""
FIELDS, EDGES, LAYOUT, SIGID, PAIRLEFT, PAIRRIGHT, VISITED, FRAME = (i<<40 for i in range(430,438))
assert not set(range(430,438)) & (set(range(350,358)) | set(range(400,408)) | set(range(410,414)))
def install(E,fail='DEAD'):
 P=E.P
 if 'MG.equal' in E.g.st:return
 from modelsignature import install as canonical_install
 canonical_install(E,fail)
 def setfield(p,field,reg):return p.a(('ALUI','mul','mg_key','mg_node',16),('ALUI','add','mg_key','mg_key',field),('STX','mg_key',FIELDS,reg))
 def constfield(p,field,val):return setfield(p.a(('LDI','mg_v',val)),field,'mg_v')
 def edge(p):return p.a(('ALUI','mul','mg_key','mg_node',1025),('ALU','add','mg_key','mg_key','mg_i'),('STX','mg_key',EDGES,'mg_lastnode'))
 def eq(name,a,b,yes,no):P(name).branch({1:yes},no,[('C64U',a,b)])
 regs=('mg_node','mg_i','mg_count','mg_end','mg_id','mg_tag','mg_attr','mg_payload','mg_top')
 P('MG.fail').a(E.rej('not covered: signature graph equality budget')).goto(fail)
 P('MG.return').ret()
 P('MG.equal').a(('COPYW','ms_blob','mg_left_blob'),('COPYW','ms_len','mg_left_len')).call('MS.canonical').a(('COPYW','mg_left_canon','ms_canon'),('COPYW','mg_left_canonlen','ms_canonlen'),('COPYW','ms_blob','mg_right_blob'),('COPYW','ms_len','mg_right_len')).call('MS.canonical').a(('COPYW','mg_right_canon','ms_canon'),('COPYW','mg_right_canonlen','ms_canonlen'),('LDI','mg_side',0),('LDI','mg_base',0),('LDI','mg_next',0),('LDI','mg_framelevel',0),('INPUSH','mg_left_canon'),('COPYW','ms_limit','mg_left_canonlen')).call('MG.root').a(('COPYW','mg_left_root','mg_lastnode'),('INPOP',),('LDI','mg_side',1),('LDI','mg_base',32768),('LDI','mg_next',0),('INPUSH','mg_right_canon'),('COPYW','ms_limit','mg_right_canonlen')).call('MG.root').a(('COPYW','mg_right_root','mg_lastnode'),('INPOP',),('ALUI','add','mg_epoch','mg_epoch',1),('LDI','mg_head',0),('LDI','mg_tail',0),('COPYW','mg_l','mg_left_root'),('COPYW','mg_r','mg_right_root')).call('MG.enqueue').goto('MG.queue')
 P('MG.new').a(('ALUI','add','mg_next','mg_next',1)).branch({2:'MG.fail'},'MG.newclear',[('CMPI','mg_next',17409)])
 P('MG.newclear').a(('ALU','add','mg_node','mg_base','mg_next'),('LDI','mg_clear',0),('LDI','mg_zero',0)).goto('MG.clear')
 P('MG.clear').a(('ALUI','mul','mg_key','mg_node',16),('ALU','add','mg_key','mg_key','mg_clear'),('STX','mg_key',FIELDS,'mg_zero'),('ALUI','add','mg_clear','mg_clear',1)).branch({1:'MG.return'},'MG.clear',[('CMPI','mg_clear',16)])
 P('MG.push').a(('ALUI','add','mg_framelevel','mg_framelevel',1)).branch({2:'MG.fail'},'MG.pushfields',[('CMPI','mg_framelevel',66)])
 p=P('MG.pushfields')
 for i,r in enumerate(regs):p.a(('ALUI','mul','mg_key','mg_framelevel',16),('ALUI','add','mg_key','mg_key',i),('STX','mg_key',FRAME,r))
 p.ret()
 p=P('MG.pop')
 for i,r in enumerate(regs):p.a(('ALUI','mul','mg_key','mg_framelevel',16),('ALUI','add','mg_key','mg_key',i),('LDX',r,'mg_key',FRAME))
 p.a(('ALUI','sub','mg_framelevel','mg_framelevel',1)).ret()
 p=P('MG.root').call('MG.new');constfield(p,3,7).call('MS.byte');setfield(p,0,'ms_byte').call('MS.u64').a(('COPYW','mg_count','ms_value'));setfield(p,4,'mg_count').a(('LDI','mg_top',1)).goto('MG.sigchildren')
 P('MG.desc').call('MG.new').a(('LDI','mg_field',0)).goto('MG.descfields')
 p=P('MG.descfields').call('MS.u64').a(('ALUI','mul','mg_key','mg_node',16),('ALU','add','mg_key','mg_key','mg_field'),('STX','mg_key',FIELDS,'ms_value'),('ALUI','add','mg_field','mg_field',1)).branch({1:'MG.desctag'},'MG.descfields',[('CMPI','mg_field',7)])
 p=P('MG.desctag').call('MS.byte').a(('COPYW','mg_tag','ms_byte'));setfield(p,7,'mg_tag').call('MS.u64').a(('COPYW','mg_payload','ms_value')).branch({(1,2):'MG.members',3:'MG.array',4:'MG.callback'},'MG.descreturn',[('RLD','mg_tag')])
 p=P('MG.members').call('MS.u64').a(('COPYW','mg_count','ms_value'));setfield(p,8,'mg_count');setfield(p,10,'mg_count').a(('LDI','mg_i',0)).goto('MG.memberloop')
 eq('MG.memberloop','mg_i','mg_count','MG.descreturn','MG.memberlayout')
 P('MG.memberlayout').a(('LDI','mg_attr',0)).goto('MG.layoutread')
 P('MG.layoutread').call('MS.u64').a(('ALUI','mul','mg_key','mg_node',1025),('ALU','add','mg_key','mg_key','mg_i'),('ALUI','mul','mg_key','mg_key',4),('ALU','add','mg_key','mg_key','mg_attr'),('STX','mg_key',LAYOUT,'ms_value'),('ALUI','add','mg_attr','mg_attr',1)).branch({1:'MG.memberchild'},'MG.layoutread',[('CMPI','mg_attr',4)])
 p=P('MG.memberchild').call('MG.push').call('MG.desc').call('MG.pop');edge(p).a(('ALUI','add','mg_i','mg_i',1)).goto('MG.memberloop')
 p=P('MG.array').call('MS.u64');setfield(p,8,'ms_value').call('MS.u64');setfield(p,9,'ms_value');constfield(p,10,1).a(('LDI','mg_i',0)).call('MG.push').call('MG.desc').call('MG.pop');edge(p).goto('MG.descreturn')
 P('MG.callback').branch({1:'MG.descreturn'},'MG.callbackread',[('CMPI','mg_payload',0)])
 P('MG.callbackread').call('MS.byte').call('MS.byte').a(('COPYW','mg_form','ms_byte')).call('MS.u64').a(('ALUI','mul','mg_id','mg_side',1025),('ALU','add','mg_id','mg_id','ms_value')).branch({0:'MG.callbackdef'},'MG.callbackref',[('RLD','mg_form')])
 P('MG.callbackref').a(('LDX','mg_lastnode','mg_id',SIGID)).goto('MG.callbackedge')
 P('MG.callbackdef').call('MG.push').call('MG.new').a(('STX','mg_id',SIGID,'mg_node')).call('MG.sigbody').call('MG.pop').goto('MG.callbackedge')
 p=P('MG.callbackedge');constfield(p,10,1).a(('LDI','mg_i',0));edge(p).goto('MG.descreturn')
 p=P('MG.sigbody');constfield(p,3,7).call('MS.byte');setfield(p,0,'ms_byte').call('MS.byte');setfield(p,5,'ms_byte').call('MS.u64').a(('COPYW','mg_count','ms_value'));setfield(p,4,'mg_count').a(('LDI','mg_top',0)).goto('MG.sigchildren')
 p=P('MG.sigchildren').a(('ALUI','add','mg_v','mg_count',1));setfield(p,10,'mg_v').a(('LDI','mg_i',0)).call('MG.push').call('MG.desc').call('MG.pop');edge(p).branch({1:'MG.sigparams'},'MG.sigstored',[('CMPI','mg_top',1)])
 P('MG.sigstored').call('MS.u64').goto('MG.sigparams')
 P('MG.sigparams').a(('LDI','mg_i',1)).goto('MG.sigloop')
 P('MG.sigloop').branch({2:'MG.sigdone'},'MG.sigchild',[('C64U','mg_i','mg_count')])
 p=P('MG.sigchild').call('MG.push').call('MG.desc').call('MG.pop');edge(p).a(('ALUI','add','mg_i','mg_i',1)).goto('MG.sigloop')
 P('MG.sigdone').branch({1:'MG.descreturn'},'MG.sigsupport',[('CMPI','mg_top',1)])
 P('MG.sigsupport').call('MS.byte').goto('MG.descreturn')
 P('MG.descreturn').a(('COPYW','mg_lastnode','mg_node')).ret()
 P('MG.enqueue').a(('ALUI','mul','mg_pair','mg_l',65536),('ALU','add','mg_pair','mg_pair','mg_r'),('LDX','mg_mark','mg_pair',VISITED)).branch({1:'MG.return'},'MG.enqueuebound',[('C64U','mg_mark','mg_epoch')])
 P('MG.enqueuebound').branch({2:'MG.fail',1:'MG.fail'},'MG.enqueueregister',[('CMPI','mg_tail',65536)])
 P('MG.enqueueregister').a(('STX','mg_pair',VISITED,'mg_epoch')).goto('MG.enqueuewrite')
 P('MG.enqueuewrite').a(('STX','mg_tail',PAIRLEFT,'mg_l'),('STX','mg_tail',PAIRRIGHT,'mg_r'),('ALUI','add','mg_tail','mg_tail',1)).ret()
 eq('MG.queue','mg_head','mg_tail','MG.yes','MG.pair')
 P('MG.pair').a(('LDX','mg_l','mg_head',PAIRLEFT),('LDX','mg_r','mg_head',PAIRRIGHT),('ALUI','add','mg_head','mg_head',1),('ALUI','mul','mg_pair','mg_l',65536),('ALU','add','mg_pair','mg_pair','mg_r'),('LDX','mg_mark','mg_pair',VISITED)).goto('MG.visit')
 P('MG.visit').a(('STX','mg_pair',VISITED,'mg_epoch'),('LDI','mg_field',0)).goto('MG.fields')
 P('MG.fields').a(('ALUI','mul','mg_key','mg_l',16),('ALU','add','mg_key','mg_key','mg_field'),('LDX','mg_a','mg_key',FIELDS),('ALUI','mul','mg_key','mg_r',16),('ALU','add','mg_key','mg_key','mg_field'),('LDX','mg_b','mg_key',FIELDS)).branch({1:'MG.fieldnext'},'MG.no',[('C64U','mg_a','mg_b')])
 P('MG.fieldnext').a(('ALUI','add','mg_field','mg_field',1)).branch({1:'MG.skipids',11:'MG.edgesstart'},'MG.fields',[('RLD','mg_field')])
 P('MG.skipids').a(('LDI','mg_field',3)).goto('MG.fields')
 P('MG.edgesstart').a(('COPYW','mg_pairleft','mg_l'),('COPYW','mg_pairright','mg_r'),('ALUI','mul','mg_key','mg_l',16),('ALUI','add','mg_key','mg_key',10),('LDX','mg_edges','mg_key',FIELDS),('LDI','mg_edge',0),('ALUI','sub','mg_key','mg_key',3),('LDX','mg_pairtag','mg_key',FIELDS)).goto('MG.edgesloop')
 eq('MG.edgesloop','mg_edge','mg_edges','MG.queue','MG.edgecompare')
 P('MG.edgecompare').branch({(1,2):'MG.edgelayout'},'MG.edgepush',[('RLD','mg_pairtag')])
 P('MG.edgelayout').a(('LDI','mg_attr',0)).goto('MG.edgelayoutread')
 P('MG.edgelayoutread').a(('ALUI','mul','mg_key','mg_pairleft',1025),('ALU','add','mg_key','mg_key','mg_edge'),('ALUI','mul','mg_key','mg_key',4),('ALU','add','mg_key','mg_key','mg_attr'),('LDX','mg_a','mg_key',LAYOUT),('ALUI','mul','mg_key','mg_pairright',1025),('ALU','add','mg_key','mg_key','mg_edge'),('ALUI','mul','mg_key','mg_key',4),('ALU','add','mg_key','mg_key','mg_attr'),('LDX','mg_b','mg_key',LAYOUT)).branch({1:'MG.edgelayoutnext'},'MG.no',[('C64U','mg_a','mg_b')])
 P('MG.edgelayoutnext').a(('ALUI','add','mg_attr','mg_attr',1)).branch({1:'MG.edgepush'},'MG.edgelayoutread',[('CMPI','mg_attr',4)])
 P('MG.edgepush').a(('ALUI','mul','mg_key','mg_pairleft',1025),('ALU','add','mg_key','mg_key','mg_edge'),('LDX','mg_l','mg_key',EDGES),('ALUI','mul','mg_key','mg_pairright',1025),('ALU','add','mg_key','mg_key','mg_edge'),('LDX','mg_r','mg_key',EDGES)).call('MG.enqueue').a(('ALUI','add','mg_edge','mg_edge',1)).goto('MG.edgesloop')
 P('MG.yes').a(('LDI','mg_equal',1)).ret()
 P('MG.no').a(('LDI','mg_equal',0)).ret()
