"""Shared model USLSIG2/3 TypeGraph framing/canonicalisation, not a host parser.
MS.canonical: ms_blob/ms_len -> ms_canon/ms_canonlen, name/nameid, count,
variadic/mode/support, resultkind/resultwidth and ms_version=2/3. All scratch uses ms_.
V3 canonical begins USLSIG3\n; V2 canonical bytes retain their legacy framing.
Input/output restored; SB scratch unspecified. Recursive base/shape become zero.
"""
LIMIT, END, KIND, WIDTH, TAG, COUNT, INDEX, ALIGN = (i<<40 for i in range(350,358))
# Separate banks from existing descriptor 350..357 and variadic 400..407.
DEPTH, SIGCOUNT, SIGINDEX, SIGCALLBASE = (i<<40 for i in range(410,414))
assert not set(range(410,414)) & (set(range(350,358)) | set(range(400,408)))
# V3 scratch is separate from legacy indexing and source LF banks 600..619.
RANK, FORMAT, NATURAL, FLAGS, KNOWN, ORIGIN, ENTRYKIND, ENTRYALIGN, OFFSET, BITOFFSET, BITWIDTH, STORAGE = (i<<40 for i in range(620,632))
assert not set(range(620,640)) & (set(range(350,358)) | set(range(400,408)) | set(range(410,414)) | set(range(430,438)) | set(range(600,620)))
def install(E,fail='DEAD'):
 P=E.P
 if 'MS.canonical' in E.g.st:return
 def eq(n,x,v,y,z):P(n).branch({1:y},z,[('LDI','ms_eq',v),('C64U',x,'ms_eq')])
 def maxv(n,x,v,nx):P(n).branch({2:'MS.fail'},nx,[('LDI','ms_max',v),('C64U',x,'ms_max')])
 def get(p,x,b):return p.a(('LDX',x,'ms_level',b))
 def put(p,x,b):return p.a(('STX','ms_level',b,x))
 P('MS.fail').a(E.rej('not covered: typed library signature')).goto(fail)
 P('MS.return').ret()
 from modelinput import u64
 u64(E,'MS.callablecap',b'\0library/callables','ms_callablecap','ms_callablepresent','MS.fail')
 P('MS.canonical').call('MS.callablecap').a(('INPUSH','ms_blob'),('COPYW','ms_limit','ms_len'),('OLEN','ms_cut'),('LDI','ms_level',0),('LDI','ms_nodes',0),('LDI','ms_signatures',0),('LDI','ms_callbacks',0),('LDI','ms_zero',0)).goto('MS.extent')
 maxv('MS.extent','ms_len',16777216,'MS.magic0')
 for i,c in enumerate(b'USLSIG2\n'):
  if i==6:P('MS.magic6').call('MS.byte').branch({50:'MS.version2',51:'MS.version3'},'MS.fail',[('RLD','ms_byte')])
  else:P('MS.magic'+str(i)).call('MS.byte').branch({c:'MS.magic'+str(i+1) if i<7 else 'MS.versionout'},'MS.fail',[('RLD','ms_byte')])
 P('MS.version2').a(('LDI','ms_version',2)).goto('MS.magic7')
 P('MS.version3').a(('LDI','ms_version',3)).goto('MS.magic7')
 eq('MS.versionout','ms_version',3,'MS.versionprefix','MS.records')
 P('MS.versionprefix').a(*[a for c in b'USLSIG3\n' for a in (('LDI','ms_byte',c),('OUTW','ms_byte'))]).goto('MS.records')
 P('MS.records').call('MS.u64').branch({1:'MS.namelen'},'MS.fail',[('LDI','ms_one',1),('C64U','ms_value','ms_one')])
 P('MS.namelen').call('MS.u64').a(('COPYW','ms_n','ms_value'),('LDI','ms_i',0),('MARK','ms_ns')).goto('MS.namebound')
 maxv('MS.namebound','ms_n',1024,'MS.nameempty')
 eq('MS.nameempty','ms_n',0,'MS.fail','MS.name')
 P('MS.name').branch({1:'MS.named'},'MS.namebyte',[('CMP','ms_i','ms_n')])
 P('MS.namebyte').call('MS.byte').branch({tuple(b'_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'):'MS.nameadv'},'MS.namedigit',[('RLD','ms_byte')])
 eq('MS.namedigit','ms_i',0,'MS.fail','MS.namedigit2')
 P('MS.namedigit2').branch({tuple(range(48,58)):'MS.nameadv'},'MS.fail',[('RLD','ms_byte')])
 P('MS.nameadv').a(('ALUI','add','ms_i','ms_i',1)).goto('MS.name')
 P('MS.named').a(('MARK','ms_ne'),('INTERN','ms_nameid','ms_ns','ms_ne'),('OLEN','ms_namecut'),('SPAN2','ms_ns','ms_ne'),('OCUT','ms_name','ms_namecut')).call('MS.byte').branch({0:'MS.defined'},'MS.fail',[('RLD','ms_byte')])
 P('MS.defined').call('MS.byte').branch({1:'MS.var'},'MS.fail',[('RLD','ms_byte')])
 P('MS.var').call('MS.bit').a(('COPYW','ms_variadic','ms_byte'),('OUTW','ms_byte')).call('MS.bit').a(('COPYW','ms_mode','ms_byte')).call('MS.u64').a(('COPYW','ms_count','ms_value')).call('MS.write64').goto('MS.countbound')
 maxv('MS.countbound','ms_count',1024,'MS.modevar')
 eq('MS.modevar','ms_variadic',1,'MS.stack','MS.modecount')
 P('MS.modecount').branch({2:'MS.stack'},'MS.register',[('LDI','ms_max',6),('C64U','ms_count','ms_max')])
 eq('MS.stack','ms_mode',1,'MS.result','MS.fail');eq('MS.register','ms_mode',0,'MS.result','MS.fail')
 P('MS.result').call('MS.desc').a(('COPYW','ms_resultkind','ms_lastkind'),('COPYW','ms_resultwidth','ms_lastwidth')).call('MS.u64').branch({1:'MS.paramsstart'},'MS.fail',[('C64U','ms_value','ms_count')])
 P('MS.paramsstart').a(('LDI','ms_pi',0)).goto('MS.params')
 P('MS.params').branch({1:'MS.support'},'MS.param',[('CMP','ms_pi','ms_count')])
 P('MS.param').call('MS.desc').a(('ALUI','add','ms_pi','ms_pi',1)).goto('MS.params')
 P('MS.support').call('MS.bit').a(('COPYW','ms_support','ms_byte')).goto('MS.supportgraph')
 eq('MS.supportgraph','ms_callbacks',0,'MS.supportend','MS.supportzero')
 eq('MS.supportzero','ms_callablecap',1,'MS.supportend','MS.supportlegacyzero')
 eq('MS.supportlegacyzero','ms_support',0,'MS.supportend','MS.fail')
 P('MS.supportend').a(('MARK','ms_pos')).branch({1:'MS.done'},'MS.fail',[('C64U','ms_pos','ms_len')])
 P('MS.done').a(('OCUT','ms_canon','ms_cut'),('BLEN','ms_canonlen','ms_canon'),('INPOP',)).ret()
 P('MS.desc').a(('ALUI','add','ms_level','ms_level',1),('ALUI','add','ms_nodes','ms_nodes',1)).goto('MS.depth')
 maxv('MS.depth','ms_level',32,'MS.nodebound');maxv('MS.nodebound','ms_nodes',16384,'MS.fields0')
 for i in range(7):
  p=P('MS.fields'+str(i))
  if i==0:put(p,'ms_limit',LIMIT)
  p.call('MS.u64')
  if i==0:put(p,'ms_value',DEPTH)
  if i in (1,2):p.a(('LDI','ms_value',0))
  if i==3:put(p,'ms_value',KIND)
  if i==4:put(p,'ms_value',WIDTH)
  if i==5:p.a(('COPYW','ms_unsigned','ms_value'))
  if i==6:put(p,'ms_value',ALIGN)
  p.call('MS.write64').goto('MS.fields'+str(i+1) if i<6 else 'MS.kindbound')
 get(P('MS.kindbound'),'ms_kind',KIND).goto('MS.kindmax')
 maxv('MS.kindmax','ms_kind',6,'MS.unsbound')
 maxv('MS.unsbound','ms_unsigned',1,'MS.width')
 get(P('MS.width'),'ms_width',WIDTH).branch({(0,6):'MS.widthzero',1:'MS.widthint',(2,4):'MS.widthptr',3:'MS.widthfp',5:'MS.widthagg'},'MS.fail',[('RLD','ms_kind')])
 eq('MS.widthzero','ms_width',0,'MS.align','MS.fail')
 maxv('MS.widthint','ms_width',8,'MS.widthintkeys')
 P('MS.widthintkeys').branch({(1,2,4,8):'MS.align'},'MS.fail',[('RLD','ms_width')])
 eq('MS.widthptr','ms_width',8,'MS.align','MS.fail')
 eq('MS.widthfp','ms_version',3,'MS.widthfp3','MS.widthfp2');maxv('MS.widthfp2','ms_width',8,'MS.widthfpkeys')
 P('MS.widthfp3').branch({(4,8,16):'MS.align'},'MS.fail',[('RLD','ms_width')])
 P('MS.widthfpkeys').branch({(4,8):'MS.align'},'MS.fail',[('RLD','ms_width')])
 eq('MS.widthagg','ms_width',0,'MS.fail','MS.widthmax');maxv('MS.widthmax','ms_width',16777216,'MS.align')
 get(P('MS.align'),'ms_align',ALIGN).branch({(0,6):'MS.alignzero'},'MS.alignnonzero',[('RLD','ms_kind')])
 eq('MS.alignzero','ms_align',0,'MS.metadata','MS.fail');eq('MS.alignnonzero','ms_align',0,'MS.fail','MS.alignmax')
 maxv('MS.alignmax','ms_align',65536,'MS.alignpow')
 P('MS.alignpow').a(('A64I','sub','ms_tmp','ms_align',1),('A64','and','ms_tmp','ms_tmp','ms_align')).branch({1:'MS.metadata'},'MS.fail',[('CMPI','ms_tmp',0)])
 eq('MS.metadata','ms_version',3,'MS.meta0','MS.tag')
 for i,(bank,reg,word) in enumerate(((RANK,'ms_rank',False),(FORMAT,'ms_format',False),(NATURAL,'ms_natural',True),(FLAGS,'ms_flags',False),(KNOWN,'ms_known',False),(ORIGIN,'ms_origin',False))):
  p=P('MS.meta'+str(i)).call('MS.u64' if word else 'MS.byte').a(('COPYW',reg,'ms_value' if word else 'ms_byte'))
  put(p,reg,bank)
  if word:p.call('MS.write64')
  else:p.a(('OUTW',reg))
  p.goto('MS.meta'+str(i+1) if i<5 else 'MS.rankbound')
 maxv('MS.rankbound','ms_rank',3,'MS.formatbound');maxv('MS.formatbound','ms_format',4,'MS.flagsbound')
 maxv('MS.flagsbound','ms_flags',3,'MS.knownbound');maxv('MS.knownbound','ms_known',3,'MS.originbound');maxv('MS.originbound','ms_origin',2,'MS.flagknown')
 P('MS.flagknown').a(('A64','and','ms_tmp','ms_flags','ms_known')).branch({1:'MS.completeorigin'},'MS.fail',[('C64U','ms_tmp','ms_flags')])
 eq('MS.completeorigin','ms_origin',1,'MS.completeknown','MS.naturalzero')
 eq('MS.completeknown','ms_known',3,'MS.completenatural','MS.fail')
 P('MS.completenatural').branch({(0,6):'MS.naturalzero'},'MS.completenonzero',[('RLD','ms_kind')])
 eq('MS.completenonzero','ms_natural',0,'MS.fail','MS.naturalzero')
 eq('MS.naturalzero','ms_natural',0,'MS.metakind','MS.naturalmax');maxv('MS.naturalmax','ms_natural',65536,'MS.naturalpow')
 P('MS.naturalpow').a(('A64I','sub','ms_tmp','ms_natural',1),('A64','and','ms_tmp','ms_tmp','ms_natural')).branch({1:'MS.metakind'},'MS.fail',[('CMPI','ms_tmp',0)])
 P('MS.metakind').branch({3:'MS.fprank'},'MS.nonfprank',[('RLD','ms_kind')])
 eq('MS.nonfprank','ms_rank',0,'MS.nonfpformat','MS.fail');eq('MS.nonfpformat','ms_format',0,'MS.tag','MS.fail')
 P('MS.fprank').branch({0:'MS.fpformat',1:'MS.rankfloat',2:'MS.rankdouble',3:'MS.ranklongdouble'},'MS.fail',[('RLD','ms_rank')])
 eq('MS.rankfloat','ms_format',1,'MS.fpformat','MS.fail');eq('MS.rankdouble','ms_format',2,'MS.fpformat','MS.fail')
 P('MS.ranklongdouble').branch({(2,3,4):'MS.fpformat'},'MS.fail',[('RLD','ms_format')])
 P('MS.fpformat').branch({0:'MS.fpunknownorigin',1:'MS.fp32',2:'MS.fp64',(3,4):'MS.fp128'},'MS.fail',[('RLD','ms_format')])
 eq('MS.fpunknownorigin','ms_origin',0,'MS.tag','MS.fail')
 eq('MS.fp32','ms_width',4,'MS.tag','MS.fail');eq('MS.fp64','ms_width',8,'MS.tag','MS.fail');eq('MS.fp128','ms_width',16,'MS.tag','MS.fail')
 put(P('MS.tag').call('MS.byte').a(('COPYW','ms_tag','ms_byte'),('OUTW','ms_byte')),'ms_tag',TAG).call('MS.u64').a(('COPYW','ms_payload','ms_value')).call('MS.write64').a(('MARK','ms_pos'),('A64','sub','ms_left','ms_limit','ms_pos')).branch({2:'MS.fail'},'MS.payloadmax',[('C64U','ms_payload','ms_left')])
 maxv('MS.payloadmax','ms_payload',16777216,'MS.payloadend')
 put(P('MS.payloadend').a(('A64','add','ms_limit','ms_pos','ms_payload')),'ms_limit',END).branch({5:'MS.aggregate',4:'MS.function'},'MS.primitive',[('RLD','ms_kind')])
 P('MS.primitive').branch({2:'MS.pointertag'},'MS.leaftag',[('RLD','ms_kind')])
 eq('MS.leaftag','ms_tag',0,'MS.empty','MS.fail')
 # V3 data pointers may carry one shallow pointee descriptor (tag 5); V2 stays tag 0.
 P('MS.pointertag').branch({0:'MS.empty',5:'MS.pointeetag'},'MS.fail',[('RLD','ms_tag')])
 eq('MS.pointeetag','ms_version',3,'MS.pointeepayload','MS.fail')
 eq('MS.pointeepayload','ms_payload',0,'MS.descdone','MS.pointeechild')
 P('MS.pointeechild').call('MS.desc').goto('MS.descdone')
 P('MS.function').a(('ALUI','add','ms_callbacks','ms_callbacks',1)).branch({0:'MS.empty',4:'MS.functionpayload'},'MS.fail',[('RLD','ms_tag')])
 eq('MS.functionpayload','ms_payload',0,'MS.descdone','MS.functiondepth')
 get(P('MS.functiondepth'),'ms_depth',DEPTH).goto('MS.functiondepthcheck')
 eq('MS.functiondepthcheck','ms_depth',1,'MS.functionalign','MS.fail')
 get(P('MS.functionalign'),'ms_align',ALIGN).goto('MS.functionaligncheck')
 eq('MS.functionaligncheck','ms_align',8,'MS.sigschema','MS.fail')
 P('MS.sigschema').call('MS.byte').branch({1:'MS.sigform'},'MS.fail',[('RLD','ms_byte')])
 P('MS.sigform').a(('OUTW','ms_byte')).call('MS.byte').a(('COPYW','ms_form','ms_byte'),('OUTW','ms_byte')).branch({0:'MS.sigdef',1:'MS.sigref'},'MS.fail',[('RLD','ms_form')])
 P('MS.sigref').call('MS.u64').goto('MS.sigrefzero')
 eq('MS.sigrefzero','ms_value',0,'MS.fail','MS.sigrefbound')
 P('MS.sigrefbound').branch({2:'MS.fail'},'MS.sigrefwrite',[('C64U','ms_value','ms_signatures')])
 P('MS.sigrefwrite').call('MS.write64').goto('MS.descdone')
 P('MS.sigdef').call('MS.u64').a(('ALUI','add','ms_signatures','ms_signatures',1)).branch({1:'MS.sigdefbound'},'MS.fail',[('C64U','ms_value','ms_signatures')])
 maxv('MS.sigdefbound','ms_signatures',1024,'MS.sigdefwrite')
 # Register before child parsing, permitting self and mutually recursive edges.
 P('MS.sigdefwrite').a(('COPYW','ms_value','ms_signatures')).call('MS.write64').call('MS.bit').a(('COPYW','ms_sigvar','ms_byte'),('OUTW','ms_byte')).call('MS.bit').a(('COPYW','ms_sigmode','ms_byte'),('OUTW','ms_byte')).call('MS.u64').call('MS.write64').goto('MS.sigcountbound')
 maxv('MS.sigcountbound','ms_value',1024,'MS.sigcountsave')
 put(put(P('MS.sigcountsave'),'ms_value',SIGCOUNT),'ms_callbacks',SIGCALLBASE).a(('COPYW','ms_sigcount','ms_value')).goto('MS.sigmodevar')
 eq('MS.sigmodevar','ms_sigvar',1,'MS.sigstack','MS.sigmodecount')
 P('MS.sigmodecount').branch({2:'MS.sigstack'},'MS.sigregister',[('LDI','ms_max',6),('C64U','ms_sigcount','ms_max')])
 eq('MS.sigstack','ms_sigmode',1,'MS.sigresult','MS.fail')
 eq('MS.sigregister','ms_sigmode',0,'MS.sigresult','MS.fail')
 get(P('MS.sigresult').call('MS.desc').call('MS.u64'),'ms_sigcount',SIGCOUNT).branch({1:'MS.sigparamsstart'},'MS.fail',[('C64U','ms_value','ms_sigcount')])
 put(P('MS.sigparamsstart').call('MS.write64').a(('LDI','ms_si',0)),'ms_si',SIGINDEX).goto('MS.sigparams')
 get(get(P('MS.sigparams'),'ms_si',SIGINDEX),'ms_sigcount',SIGCOUNT).branch({1:'MS.sigsupport'},'MS.sigparam',[('CMP','ms_si','ms_sigcount')])
 P('MS.sigparam').call('MS.desc').goto('MS.signext')
 put(get(P('MS.signext'),'ms_si',SIGINDEX).a(('ALUI','add','ms_si','ms_si',1)),'ms_si',SIGINDEX).goto('MS.sigparams')
 get(P('MS.sigsupport').call('MS.bit').a(('COPYW','ms_sigsupport','ms_byte')),'ms_callbase',SIGCALLBASE).branch({1:'MS.sigsupportwrite'},'MS.sigsupportzero',[('C64U','ms_callbase','ms_callbacks')])
 eq('MS.sigsupportzero','ms_callablecap',1,'MS.sigsupportwrite','MS.sigsupportlegacyzero')
 eq('MS.sigsupportlegacyzero','ms_sigsupport',0,'MS.sigsupportwrite','MS.fail')
 P('MS.sigsupportwrite').a(('OUTW','ms_sigsupport')).goto('MS.descdone')
 eq('MS.empty','ms_payload',0,'MS.descdone','MS.fail')
 P('MS.aggregate').branch({(1,2):'MS.members',3:'MS.array'},'MS.fail',[('RLD','ms_tag')])
 put(P('MS.members').call('MS.u64').call('MS.write64'),'ms_value',COUNT).goto('MS.membermax')
 eq('MS.membermax','ms_version',3,'MS.membermax3','MS.membermax2');maxv('MS.membermax2','ms_value',64,'MS.memberstart');maxv('MS.membermax3','ms_value',128,'MS.memberstart')
 put(P('MS.memberstart').a(('LDI','ms_mi',0)),'ms_mi',INDEX).goto('MS.memberloop')
 get(get(P('MS.memberloop'),'ms_mi',INDEX),'ms_mc',COUNT).branch({1:'MS.descdone'},'MS.memberversion',[('CMP','ms_mi','ms_mc')])
 eq('MS.memberversion','ms_version',3,'MS.entryordinal','MS.member0')
 for i,bank in enumerate((OFFSET,BITOFFSET,BITWIDTH,STORAGE)):
  put(P('MS.member'+str(i)).call('MS.u64').call('MS.write64'),'ms_value',bank).goto('MS.member'+str(i+1) if i<3 else 'MS.child')
 P('MS.entryordinal').call('MS.u64').branch({1:'MS.entryordinalwrite'},'MS.fail',[('C64U','ms_value','ms_mi')])
 put(P('MS.entryordinalwrite').call('MS.write64').call('MS.byte').a(('OUTW','ms_byte')),'ms_byte',ENTRYKIND).goto('MS.entrykindbound')
 maxv('MS.entrykindbound','ms_byte',4,'MS.entryalignment')
 put(P('MS.entryalignment').call('MS.u64').call('MS.write64'),'ms_value',ENTRYALIGN).goto('MS.entryalignzero')
 eq('MS.entryalignzero','ms_value',0,'MS.fail','MS.entryalignmax');maxv('MS.entryalignmax','ms_value',65536,'MS.entryalignpow')
 P('MS.entryalignpow').a(('A64I','sub','ms_tmp','ms_value',1),('A64','and','ms_tmp','ms_tmp','ms_value')).branch({1:'MS.member0'},'MS.fail',[('CMPI','ms_tmp',0)])
 P('MS.child').call('MS.desc').goto('MS.childversion')
 eq('MS.childversion','ms_version',3,'MS.entrycheck','MS.membernext')
 p=P('MS.entrycheck')
 for bank,reg in ((ENTRYKIND,'ms_entrykind'),(OFFSET,'ms_offset'),(BITOFFSET,'ms_bitoffset'),(BITWIDTH,'ms_bitwidth'),(STORAGE,'ms_storage'),(WIDTH,'ms_parentwidth')):get(p,reg,bank)
 p.branch({(0,4):'MS.entryordinary',(1,2):'MS.entrybit',3:'MS.entrybarrier'},'MS.fail',[('RLD','ms_entrykind')])
 eq('MS.entryordinary','ms_bitoffset',0,'MS.entryordinarywidth','MS.fail');eq('MS.entryordinarywidth','ms_bitwidth',0,'MS.entrystorage','MS.fail')
 P('MS.entrystorage').branch({1:'MS.entryanonymous'},'MS.fail',[('C64U','ms_storage','ms_lastwidth')])
 eq('MS.entryanonymous','ms_entrykind',4,'MS.entryanontag','MS.entryfit')
 P('MS.entryanontag').branch({(1,2):'MS.entryfit'},'MS.fail',[('RLD','ms_lasttag')])
 eq('MS.entrybit','ms_bitwidth',0,'MS.fail','MS.entryinteger')
 eq('MS.entrybarrier','ms_bitwidth',0,'MS.entrybarrieroffset','MS.fail');eq('MS.entrybarrieroffset','ms_bitoffset',0,'MS.entryinteger','MS.fail')
 eq('MS.entryinteger','ms_lastkind',1,'MS.entryintegerdepth','MS.fail');eq('MS.entryintegerdepth','ms_lastdepth',0,'MS.entryintegertag','MS.fail');eq('MS.entryintegertag','ms_lasttag',0,'MS.entryintegerstorage','MS.fail')
 P('MS.entryintegerstorage').branch({1:'MS.entryintegerkind'},'MS.fail',[('C64U','ms_storage','ms_lastwidth')])
 eq('MS.entryintegerkind','ms_entrykind',3,'MS.entrybarrierfit','MS.entrybitbound')
 P('MS.entrybitbound').branch({2:'MS.fail'},'MS.entrybitcalc',[('LDI','ms_bits',64),('C64U','ms_bitwidth','ms_bits')])
 P('MS.entrybitcalc').a(('A64I','mul','ms_bits','ms_storage',8),('A64','add','ms_tmp','ms_bitoffset','ms_bitwidth')).branch({2:'MS.fail'},'MS.entrybitoffsetbound',[('C64U','ms_bitoffset','ms_bits')])
 P('MS.entrybitoffsetbound').branch({2:'MS.fail'},'MS.entryfit',[('C64U','ms_tmp','ms_bits')])
 P('MS.entryfit').branch({2:'MS.fail'},'MS.entryfitsize',[('C64U','ms_offset','ms_parentwidth')])
 P('MS.entryfitsize').a(('A64','sub','ms_tmp','ms_parentwidth','ms_offset')).branch({2:'MS.fail'},'MS.membernext',[('C64U','ms_storage','ms_tmp')])
 P('MS.entrybarrierfit').branch({2:'MS.fail'},'MS.membernext',[('C64U','ms_offset','ms_parentwidth')])
 put(get(P('MS.membernext'),'ms_mi',INDEX).a(('ALUI','add','ms_mi','ms_mi',1)),'ms_mi',INDEX).goto('MS.memberloop')
 P('MS.array').call('MS.u64').a(('COPYW','ms_arraycount','ms_value')).call('MS.write64').goto('MS.arraycountmax')
 maxv('MS.arraycountmax','ms_arraycount',16777216,'MS.arraystride')
 P('MS.arraystride').call('MS.u64').a(('COPYW','ms_stride','ms_value')).call('MS.write64').goto('MS.arraystridemax')
 maxv('MS.arraystridemax','ms_stride',16777216,'MS.arraysize')
 get(P('MS.arraysize').a(('A64','mul','ms_tmp','ms_arraycount','ms_stride')),'ms_width',WIDTH).branch({1:'MS.arraychild'},'MS.fail',[('C64U','ms_tmp','ms_width')])
 P('MS.arraychild').call('MS.desc').goto('MS.descdone')
 get(P('MS.descdone').a(('MARK','ms_pos')),'ms_end',END).branch({1:'MS.descreturn'},'MS.fail',[('C64U','ms_pos','ms_end')])
 get(get(get(get(get(P('MS.descreturn'),'ms_limit',LIMIT),'ms_lastkind',KIND),'ms_lastwidth',WIDTH),'ms_lastdepth',DEPTH),'ms_lasttag',TAG).a(('ALUI','sub','ms_level','ms_level',1)).ret()
 P('MS.bit').call('MS.byte').branch({(0,1):'MS.return'},'MS.fail',[('RLD','ms_byte')])
 P('MS.byte').a(('MARK','ms_pos')).branch({0:'MS.byteok'},'MS.fail',[('C64U','ms_pos','ms_limit')])
 P('MS.byteok').a(('BYTE','ms_byte'),('ADV',)).ret()
 P('MS.u64').a(('LDI','ms_value',0),('LDI','ms_shift',0)).goto('MS.u64loop')
 P('MS.u64loop').call('MS.byte').a(('A64','shl','ms_part','ms_byte','ms_shift'),('A64','or','ms_value','ms_value','ms_part'),('ALUI','add','ms_shift','ms_shift',8)).branch({1:'MS.return'},'MS.u64loop',[('CMPI','ms_shift',64)])
 P('MS.write64').a(('LDI','ms_shift',0)).goto('MS.writeloop')
 P('MS.writeloop').a(('A64','shr','ms_part','ms_value','ms_shift'),('OUTW','ms_part'),('ALUI','add','ms_shift','ms_shift',8)).branch({1:'MS.return'},'MS.writeloop',[('CMPI','ms_shift',64)])
