#!/bin/sh
# exec/c/chain.sh FILE... -- source to tape through ONE generic executor
# (exec/c/run.c) and three tables: E2 (preprocess), E1 (lex, typed), E3
# (parse).  Each stage runs as its own process; the reference's tape is only
# compared with, never fed forward.  The tables are generated by Python.
#
# Per file, the stages run in order and the first that does not accept stops
# the chain; its stage and first stderr line are kept.  Verdicts:
#   equal        all three accept and the tape equals `ua_ref -S`
#   not-covered  a stage rejects with `not covered: ...`
#   rejected     a stage rejects for another reason (a language error, a
#                stray char) -- listed, not counted as covered or as bad
#   bad          the tape differs; or a stage exits other than 0/1 (bad
#                table, out of steps, killed); or the reference times out or
#                dies on a signal -- a tool failure is never hidden
# With CHAINKEEP=LIST every listed file must be `equal` (and be an input).
# Every step is bounded (AGENTS.md: 60 s).
set -u
R=$(cd "$(dirname "$0")/../.." && pwd); cd "$R"
[ $# -gt 0 ] || { echo "no input files"; exit 1; }
UA=${UA:-/tmp/ua_ref}; . "$R/tests/lib.sh"; ua_ready
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
b() { perl -e 'alarm shift; exec @ARGV' "$@"; }
b 60 cc -O2 -std=c99 -w -o "$T/run" exec/c/run.c || { echo "chain: cc failed"; exit 1; }
b 60 python3 exec/pp/gen.py "$T/e2.json" >/dev/null 2>&1 || { echo "chain: E2 gen failed"; exit 1; }
b 60 python3 exec/lex/gen.py --typed "$T/e1.json" >/dev/null 2>&1 || { echo "chain: E1 gen failed"; exit 1; }
b 60 python3 exec/parse2/gen2.py "$T/e3.json" >/dev/null 2>&1 || { echo "chain: E3 gen failed"; exit 1; }
for s in e2 e1 e3; do b 60 python3 exec/c/tbl.py "$T/$s.json" "$T/$s.tbl" || { echo "chain: tbl $s failed"; exit 1; }; done
if [ -n "${CHAINKEEP:-}" ]; then
    [ -s "$CHAINKEEP" ] || { echo "chain: CHAINKEEP names an empty list"; exit 1; }
fi
eq=0; nc=0; rj=0; bad=0; : > "$T/equal"
for f in "$@"; do
    b 10 "$UA" "$f" -S -o - > "$T/ref" 2>/dev/null; rr=$?
    stage=""; rc=0; why=""
    in=$f
    for s in e2 e1 e3; do
        case $s in
        e2) b 10 "$T/run" "$T/e2.tbl" "$in" "$f" include > "$T/$s.out" 2> "$T/$s.err"; rc=$? ;;
        e1) b 10 "$T/run" "$T/e1.tbl" "$in" > "$T/$s.out" 2> "$T/$s.err"; rc=$? ;;
        e3) b 10 "$T/run" "$T/e3.tbl" "$in" "$f" > "$T/$s.out" 2> "$T/$s.err"; rc=$? ;;
        esac
        [ $rc -eq 0 ] || { stage=$s; why=$(head -1 "$T/$s.err"); break; }
        in=$T/$s.out
    done
    if [ $rr -ge 128 ] || [ $rr -lt 0 ]; then v=bad; why="reference exited $rr"
    elif [ -z "$stage" ]; then
        if [ $rr -eq 0 ] && cmp -s "$T/e3.out" "$T/ref"; then v=equal; else v=bad; why="tape differs (reference rc=$rr)"; fi
    elif [ $rc -ne 1 ]; then v=bad; why="$stage exited $rc: $why"
    else case "$why" in "reject: not covered"*) v=not-covered ;; *) v=rejected ;; esac
    fi
    case $v in
    equal) eq=$((eq+1)); echo "$f" >> "$T/equal" ;;
    not-covered) nc=$((nc+1)) ;;
    rejected) rj=$((rj+1)); [ -n "${CHAINV:-}" ] && echo "  rejected $f  at $stage: $why" ;;
    bad) bad=$((bad+1)); echo "  BAD $f  ${stage:+at $stage: }$why" ;;
    esac
    [ -n "${CHAINV:-}" ] && [ "$v" = not-covered ] && echo "  not-covered $f  at $stage: ${why#reject: }"
done
lost=0
if [ -n "${CHAINKEEP:-}" ]; then
    for k in $(cat "$CHAINKEEP"); do
        grep -qx "$k" "$T/equal" || { echo "  LOST $k"; lost=$((lost+1)); }
    done
fi
echo "chain  files $#   equal $eq   not-covered $nc   rejected $rj   bad $bad${CHAINKEEP:+   lost $lost}"
[ $bad -eq 0 ] && [ $lost -eq 0 ] && [ $eq -gt 0 ]
