#!/usr/bin/env python3
"""Programs whose DATA is awkward, written to order. [A-41]

The corpus grew from things people wanted to compile, so its data symbols
happen to be declared in address order and defined once.  A compiler's data
layout has to survive more than that, and the one input that did -- unisacc
compiling itself -- segfaulted the back end for every target while all 90
probes stayed green.

So these are generated: globals whose declaration order is not their
allocation order, tentative definitions completed later, string literals
allocated between globals, zero-filled arrays next to initialised ones, and
blobs whose length is not a multiple of 8 (the layout keeps each blob's
address mod 8, which is only visible when the lengths disagree).

Each file is a function of its seed alone, so a failure names a file that
can be regenerated byte for byte.
"""
import sys


def gen(seed, nsym):
    """One program.  Deterministic: mulberry32, the generator the rest of
    this project uses, so a seed means the same thing everywhere."""
    state = [seed & 0xFFFFFFFF]

    def rnd(n):
        state[0] = (state[0] + 0x6D2B79F5) & 0xFFFFFFFF
        t = state[0]
        t = (t ^ (t >> 15)) * (t | 1) & 0xFFFFFFFF
        t ^= (t + ((t ^ (t >> 7)) * (t | 61) & 0xFFFFFFFF)) & 0xFFFFFFFF
        t &= 0xFFFFFFFF
        return ((t ^ (t >> 14)) >> 3) % n

    L = ["#include <stdio.h>"]
    kinds = []
    for i in range(nsym):
        k = rnd(5)
        kinds.append(k)
        if k == 0:                        # initialised scalar
            L.append("int g%d = %d;" % (i, rnd(1000)))
        elif k == 1:                      # zero scalar -> bss
            L.append("int g%d;" % i)
        elif k == 2:                      # array, length not a multiple of 8
            L.append("char g%d[%d];" % (i, 1 + rnd(23)))
        elif k == 3:                      # initialised array
            n = 1 + rnd(5)
            L.append("int g%d[%d] = {%s};" %
                     (i, n, ", ".join(str(rnd(100)) for _ in range(n))))
        else:                             # tentative, completed further down
            L.append("int g%d;" % i)

    # the completions, in an order of their own -- this is what makes the
    # declaration order differ from the allocation order
    for i in range(nsym - 1, -1, -1):
        if kinds[i] == 4:
            L.append("int g%d = %d;" % (i, 1 + rnd(90)))

    # string literals land in the data too, and these sit BETWEEN the
    # globals above and the ones below
    L.append("char *s%d(void) { return \"lit%d\"; }" % (0, seed))

    L.append("int main(void) {")
    L.append("    long sum = 0;")
    for i in range(nsym):
        if kinds[i] == 2:
            L.append("    g%d[0] = %d; sum = sum + g%d[0];" % (i, 1 + rnd(9), i))
        elif kinds[i] == 3:
            L.append("    sum = sum + g%d[0];" % i)
        else:
            L.append("    sum = sum + g%d;" % i)
    L.append("    printf(\"%s %ld\\n\", s0(), sum);")
    L.append("    return 0;")
    L.append("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    out = sys.argv[1]
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 12
    for seed in range(1, n + 1):
        open("%s/gen%02d.c" % (out, seed), "w").write(gen(seed, 3 + seed % 9))
    print(n)
