#!/usr/bin/env python3
"""Script inventory (0.0.15 R15-1): every test/check script and where it runs.

Gated  = named in a job of `tests/gate.sh --list --com` or `tests/all.sh --list`,
         in .github/workflows/*, or reached from one of those scripts by path
         (transitive over .sh/.py sources).
Library = imported (python) or sourced (sh) by a gated script.
Orphan = neither; each must be deleted, gated, or listed in tests/ungated-checks.tsv
         with a disposition.  `--check` fails on an unlisted orphan; `--write`
         refreshes tests/INVENTORY.md.
"""
import pathlib, re, subprocess, sys
R = pathlib.Path(__file__).resolve().parents[1]
SCRIPTS = sorted({p for pat in ('tests/*.sh', 'tests/*.py', 'tests/*.cx', 'exec/**/*check*.py', 'exec/**/*check*.sh', 'exec/**/*.sh')
                  for p in R.glob(pat) if p.is_file() and '__pycache__' not in p.parts and 'build' not in p.parts})
def rel(p): return str(p.relative_to(R))
def text(p):
    try: return p.read_text(errors='ignore')
    except OSError: return ''
roots = [R / 'tests/gate.sh', R / 'tests/all.sh', R / 'tests/release.sh'] + sorted((R / '.github/workflows').glob('*.yml'))
jobs = {}
gate_src = text(R / 'tests/gate.sh')
# job name -> command text, from `job NAME CMD...` lines (loops expand to several names; keep the pattern)
for m in re.finditer(r'^\s*(?:for [^;]*; do )?job\s+(\S+)\s+(.*)$', gate_src, re.M):
    jobs.setdefault(m.group(1), m.group(2))
names = {rel(p): p for p in SCRIPTS}
def refs(src):
    out = set()
    for n in names:
        b = pathlib.Path(n).name
        if n in src or ('/' + b) in src or re.search(r'(^|[\s"\'(=/])' + re.escape(b) + r'\b', src):
            out.add(n)
    return out
reached, frontier = set(), set()
for r in roots: frontier |= refs(text(r))
while frontier:
    n = frontier.pop()
    if n in reached: continue
    reached.add(n); frontier |= refs(text(names[n])) - reached
# python imports by module name
mods = {pathlib.Path(n).stem: n for n in names if n.endswith('.py')}
imported = set()
for n in reached:
    for m in re.findall(r'^\s*(?:from|import)\s+([A-Za-z_][\w]*)', text(names[n]), re.M):
        if m in mods: imported.add(mods[m])
listed = {l.split('\t')[0] for l in text(R / 'tests/ungated-checks.tsv').splitlines() if l and not l.startswith('#')}
rows, orphans = [], []
for n in names:
    where = [j for j, c in jobs.items() if pathlib.Path(n).name in c]
    if where: kind = 'gate: ' + ', '.join(sorted(where)[:4]) + (' ...' if len(where) > 4 else '')
    elif n in reached: kind = 'reached from a gate/CI script'
    elif n in imported: kind = 'library (imported by a gated script)'
    elif n in listed: kind = 'listed in tests/ungated-checks.tsv'
    else: kind = 'ORPHAN'; orphans.append(n)
    rows.append((n, kind))
if '--write' in sys.argv:
    out = ['# Script inventory', '', 'Generated by `python3 tests/inventory.py --write` (0.0.15 R15-1). Every test or check script and where it runs; an ORPHAN must be deleted, gated, or given a disposition in `tests/ungated-checks.tsv`.', '',
           '| Script | Where it runs |', '|---|---|'] + ['| `%s` | %s |' % r for r in rows]
    (R / 'tests/INVENTORY.md').write_text('\n'.join(out) + '\n')
print('inventory  scripts %d   gated/reached %d   library %d   listed %d   orphan %d' % (
    len(rows), sum(1 for r in rows if r[1].startswith(('gate', 'reached'))), sum(1 for r in rows if r[1].startswith('library')),
    sum(1 for r in rows if r[1].startswith('listed')), len(orphans)))
for o in orphans: print('  ORPHAN ' + o)
sys.exit(1 if ('--check' in sys.argv and orphans) else 0)
