"""The E1 delta as a gold stage: key = the finite observation, class = the step.

    python3 exec/lex/stage.py delta.json tsv OUT.tsv    write it in the gold-table form
    python3 exec/lex/stage.py delta.json build          try the project's construction

Fields: q (the 335 states) and v (0..256): the value of the ONE component
state q reads -- the byte (0..255, 256 = EOF), or for a t-state the stack
top as an index into GAMMA, or for an r-state the result code.  Values past a
t- or r-state's domain are never observed; they carry the delta's own
`unreachable` entry, so the stage is total over the product (the gold-table
contract).  Heads: nxt (next state, HALT included) and seq (action-sequence id).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)

from unisa.gold import Stage                     # noqa: E402

GAMMA = ["BOT", "P"] + ["D%d" % d for d in range(10)]


def stage(d):
    S = d["states"]
    names = list(S)
    unr = [i for i, s in enumerate(d["seqs"]) if s == [["REJECT", "unreachable"]]]
    assert len(unr) == 1
    U = ("HALT", unr[0])
    tab = {}
    for q, (mode, row) in S.items():
        for v in range(257):
            if mode == "b":
                e = row[str(v)]
            elif mode == "t":
                e = row[GAMMA[v]] if v < len(GAMMA) else U
            else:
                e = row[str(v)] if str(v) in row else U
            tab[(q, str(v))] = {"nxt": e[0], "seq": str(e[1])}
    fields = [("q", tuple(names)), ("v", tuple(str(v) for v in range(257)))]
    heads = [("nxt", tuple(names + ["HALT"]), None),
             ("seq", tuple(str(k) for k in range(len(d["seqs"]))), None)]
    return Stage("e1delta", fields, heads, lambda q, v: tab[(q, v)], cfg=None), tab


def write_tsv(S, tab, out):
    with open(out, "w") as f:
        f.write("# stage e1delta: %d keys, generated by exec/lex/stage.py from exec/lex/gen.py -- do not edit\n"
                % len(tab))
        for fn, vo in S.fields:
            f.write("\t".join(["#field", fn] + list(vo)) + "\n")
        for hn, cl, _ in S.heads:
            f.write("\t".join(["#head", hn, "-"] + list(cl)) + "\n")
        f.write("q\tv\t=> nxt\t=> seq\n")
        for q, v in S.keys():
            lab = tab[(q, v)]
            f.write("%s\t%s\t%s\t%s\n" % (q, v, lab["nxt"], lab["seq"]))


def main():
    d = json.load(open(sys.argv[1]))
    S, tab = stage(d)
    if sys.argv[2] == "tsv":
        write_tsv(S, tab, sys.argv[3])
        print("e1delta  keys %d  fields q %d v 257  classes nxt %d seq %d"
              % (len(tab), len(S.fields[0][1]), len(S.heads[0][1]), len(S.heads[1][1])))
        return 0
    import time
    from unisa.construct import build_net, Domain
    t = time.time()
    D = Domain(S)
    print("domain: keys %d, quotient %s -> %d keys  (%.1f s)"
          % (len(D.okeys), [len(g) for g in D.groups], D.n, time.time() - t), flush=True)
    p = build_net(S)
    print("built: H %d units, h0 %d, W2 values %s  (%.1f s)"
          % (p["H"], p["h0"], sorted(p["wvals"]), time.time() - t), flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
