"""Emit the decision layer as C: model data + the integer kernel. [K-5]

The point of the thesis is that deployment is "inferencer + executor + model
data".  This writes exactly that, in C, from the constructed integer nets:

  unisa_model.h  the units as a byte blob plus dimensions
  unisa_boot.c   the kernel (embed -> match -> add -> argmax) and a self-test

The blob avoids nested array initialisers, which our own C subset does not yet
parse -- so the generated C is inside the subset and unisa can compile it.
"""
from .gold import STAGES, ALL


def maskw(st):
    """How many u64 words this stage's literal masks need.  One was enough
    until TOKS grew past 64 (`~` plus the remaining compound assignments took
    it to 67) and the blob writer overflowed.  It is per STAGE, not global:
    only `parse` has a vocabulary that big, and paying two words everywhere
    would have cost 5.7 KB of blob.  [K-5a]"""
    w = 1
    for (_, v) in STAGES[st].fields:
        w = max(w, (len(v) + 63) // 64)
    return w


def _blob(nets):
    """unit records, flat: [nf][fieldmasks...][nw2][(unit,cls,w)...]

    w is two bytes: the construction's weights are priority levels, and the
    type table with a floating axis needs 256 -- one past what a byte held."""
    out = bytearray()
    meta = []
    for st in ALL:
        n = nets[st]
        S = STAGES[st]
        m = len(S.fields)
        W = maskw(st)
        start = len(out)
        # per unit: m little-endian u64 literal masks (0 = don't care)
        cols = [[0] * sum(len(v) for (_, v) in S.fields) for _ in range(n.H)]
        for c, us in enumerate(n.feeds):
            for j in us:
                cols[j][c] = 1
        offs, o = [], 0
        for (_, v) in S.fields:
            offs.append(o)
            o += len(v)
        for j in range(n.H):
            for i, (_, v) in enumerate(S.fields):
                mask = 0
                for k in range(len(v)):
                    if cols[j][offs[i] + k]:
                        mask |= 1 << k
                if mask == (1 << len(v)) - 1:
                    mask = 0                      # every value -> don't care
                for wi in range(W):
                    out += ((mask >> (64 * wi)) & ((1 << 64) - 1)) \
                        .to_bytes(8, "little")
        ents = []
        for hi, (hn, cl) in enumerate(n.heads):
            for j in range(n.H):
                for (k, w) in n.w2[hn][j]:
                    ents.append((j, hi, k, w))
        out += len(ents).to_bytes(4, "little")
        for (j, hi, k, w) in ents:
            out += bytes([j & 0xFF, (j >> 8) & 0xFF, hi, k & 0xFF,
                          (k >> 8) & 0xFF, w & 0xFF, (w >> 8) & 0xFF])
        meta.append((st, m, n.H, len(n.heads), start,
                     [len(cl) for _, cl in n.heads],
                     [len(v) for (_, v) in S.fields], W))
    return bytes(out), meta


def _cases(nets):
    """Every key of every stage, with the expected class index per head."""
    out = bytearray()
    n = 0
    for si, st in enumerate(ALL):
        S = STAGES[st]
        net = nets[st]
        vidx = [{v: i for i, v in enumerate(vo)} for (_, vo) in S.fields]
        hidx = [{c: i for i, c in enumerate(cl)} for _, cl in net.heads]
        for kv in S.keys():
            lab = S.label(*kv)
            for hi, (hn, cl) in enumerate(net.heads):
                out += bytes([si, hi])
                for i in range(4):
                    out += bytes([vidx[i][kv[i]] if i < len(kv) else 0])
                e = hidx[hi][lab[hn]]
                out += bytes([e & 0xFF, (e >> 8) & 0xFF])
                n += 1
    return bytes(out), n


def _cstr(b, name):
    esc = "".join("\\x%02x" % x for x in b)
    ch = [esc[i:i + 80] for i in range(0, len(esc), 80)]
    return ["char *%s =" % name] + ['  "%s"' % c for c in ch[:-1]] + \
        ['  "%s";' % ch[-1]]


# The generated files: the model changes whenever a table does, the kernel
# does not, so they are written apart. [K-5]
MODEL_INC = "unisa_model.inc"
CASES_INC = "unisa_cases.inc"
HEADERS_INC = "unisa_headers.inc"


def emit_headers(incdir, path):
    """The C library, carried INSIDE the compiler. [W-15] [S-11]

    A compiler people run from anywhere cannot look for `include/` beside the
    working directory -- the single-file build has no directory at all.  So
    the headers travel in the binary, and the filesystem still wins when it
    has them, which keeps editing `include/` during development immediate.
    """
    import os as _os
    names = sorted(n for n in _os.listdir(incdir) if n.endswith(".h"))
    L = ['/* generated by `unisa emit-kernel` -- do not edit.',
         ' * The headers this compiler answers `#include <x.h>` with, packed',
         ' * as text: a shipped binary has no include/ to read. */', '',
         'char *HDR_NAMES = "%s";' % "".join(n + "\\000" for n in names),
         '#define NHDR %d' % len(names), '']
    total = 0
    for i, n in enumerate(names):
        b = open(_os.path.join(incdir, n), "rb").read()
        total += len(b)
        L += _cstr(b, "HDR_%d" % i)
        L += ['']
    L += ['/* the i-th header\'s text */',
          'char *hdr_text(int i) {']
    for i in range(len(names)):
        L.append('  if (i == %d) return HDR_%d;' % (i, i))
    L += ['  return 0;', '}', '']
    open(path, "w").write("\n".join(L) + "\n")
    return len(names), total


def emit_core(nets, path):
    """The kernel, and beside it the model. [K-5]

    Two files, because they change for different reasons: `unisa_model.inc`
    is the weights and the vocabularies -- it turns over whenever a table
    does -- and `unisa_core.c` is the integer kernel, which does not.  A
    weight rebuild then shows up as a diff in the data alone.
    """
    import os as _os
    model_path = _os.path.join(_os.path.dirname(path), MODEL_INC)
    blob, meta = _blob(nets)
    L = ['/* generated by `unisa emit-kernel` -- do not edit.',
         ' * The model: weights, stage dimensions and vocabularies.  The',
         ' * kernel that reads them is in unisa_core.c. [K-5] */', '']
    for i, (st, m, H, nh, off, ncls, vlen, mw) in enumerate(meta):
        L.append('#define S_%s %d' % (st.upper(), i))
    L += ['']
    L += _cstr(blob, "MODEL")
    L += ['', '#define NSTAGE %d' % len(meta),
          '']
    L += ['int STAGE_M[%d];' % len(meta), 'int STAGE_H[%d];' % len(meta),
          'int STAGE_OFF[%d];' % len(meta),
          'int STAGE_NCLS[%d];' % (len(meta) * 12),
          'int STAGE_MW[%d];' % len(meta),
          'int STAGE_VN[%d];' % (len(meta) * 4),
          'int act[4096];', 'int z[512];', '']
    L += ['int model_dims(void) {']
    for i, (st, m, H, nh, off, ncls, vlen, mw) in enumerate(meta):
        L.append('  STAGE_M[%d] = %d; STAGE_H[%d] = %d; STAGE_OFF[%d] = %d;'
                 '  STAGE_MW[%d] = %d;' % (i, m, i, H, i, off, i, mw))
        for k, c in enumerate(ncls):
            L.append('  STAGE_NCLS[%d] = %d;' % (i * 12 + k, c))
        for f, n in enumerate(vlen):
            L.append('  STAGE_VN[%d] = %d;' % (i * 4 + f, n))
    L += ['  return %d;' % len(meta), '}', '']
    # vocabularies the C side needs, packed as NUL-separated strings so no
    # array-of-pointer initialiser is required (our subset has none yet)
    from .gold import (TOKS, PRODS, LEXACT, DIRS, PPACT, NT, TYS, TOPS,
                       TYOUT, CTX, KIND, ACTS, FAMILY, FLAVOR, RECIPE)
    from .front.lex import TYPEKW
    # type / scope / irsel: the C front end asks these tables too, with the
    # same keys the Python walker uses -- a stage the self-hosted compiler
    # decides in hand-written code is a stage the thesis does not cover.
    for nm, vals in (("TOKV", TOKS), ("PRODV", PRODS), ("ACTV", LEXACT),
                     ("TYPEV", TYPEKW), ("DIRV", DIRS), ("PPACTV", PPACT),
                     ("NTV", NT), ("TYSV", TYS), ("TOPSV", TOPS),
                     ("TYOUTV", TYOUT), ("SCTXV", CTX), ("SKINDV", KIND),
                     ("SACTV", ACTS), ("IRFAMV", FAMILY), ("IRFLAV", FLAVOR),
                     ("IRRECV", RECIPE)):
        packed = "".join(v + "\\0" for v in vals)
        L += ['char *%s = "%s";' % (nm, packed),
              '#define N%s %d' % (nm, len(vals)), '']
    # the back end's stages -- isel, abi, enc, reloc, regmap: every field and every
    # head, named by stage.  The self-hosted compiler lowers its own tape by
    # asking these, exactly as unisa/lower.py does; a head's classes are the
    # NET's, in the net's order, which is what infer() returns an index into.
    for st in ("enc", "reloc", "regmap", "tyinfo", "pfconv", "peep", "opinfo", "prec", "isel", "abi"):
        S = STAGES[st]
        for i, (_, vals) in enumerate(S.fields):
            nm = "BF_%s_%d" % (st.upper(), i)
            # \\000, three digits: a value that starts with a digit (a
            # syscall number) would otherwise extend the octal escape
            packed = "".join(str(v) + "\\000" for v in vals)
            L += ['char *%s = "%s";' % (nm, packed),
                  '#define N%s %d' % (nm, len(vals)), '']
        for hi, (hn, cl) in enumerate(nets[st].heads):
            nm = "BH_%s_%s" % (st.upper(), hn.upper())
            packed = "".join(str(v) + "\\000" for v in cl)
            L += ['char *%s = "%s";' % (nm, packed),
                  '#define N%s %d' % (nm, len(cl)),
                  '#define HD_%s_%s %d' % (st.upper(), hn.upper(), hi), '']
    open(model_path, "w").write("\n".join(L) + "\n")
    K = ['/* generated by `unisa emit-kernel` -- do not edit.',
         ' * The decision layer as C: the integer kernel [K-5].  The model it',
         ' * reads is the file included below.',
         ' * No softmax, no libm, no malloc, no multiply, no float. */', '',
         '#include "%s"' % MODEL_INC, '']
    K += [KERNEL_BODY.split('int main(void)')[0]]
    open(path, "w").write("\n".join(K) + "\n")
    return len(blob), len(meta)


def emit_self(nets, path):
    """The kernel plus a full-gold self test, over the shared model.

    `#include "x"` is looked up beside the including file by cc and by
    unisacc alike, so this compiles either way -- and the build scripts that
    want one flat file concatenate the pieces instead."""
    import os as _os
    cases_path = _os.path.join(_os.path.dirname(path), CASES_INC)
    blob, meta = _blob(nets)
    cases, ncase = _cases(nets)
    C = ['/* generated by `unisa emit-kernel` -- do not edit.',
         ' * Every key of every stage, with the class the gold gives it: what',
         ' * the self test enumerates [P-3]. */', '']
    C += _cstr(cases, "CASES")
    C += ['', '#define NCASE %d' % ncase, '']
    open(cases_path, "w").write("\n".join(C) + "\n")
    L = ['/* generated by `unisa emit-kernel` -- do not edit.',
         ' * The kernel, self-testing over the FULL gold corpus [P-3].  The',
         ' * model and the cases are the files included below -- `"x"` is',
         ' * looked up beside this file, by cc and by unisacc alike.',
         ' * No softmax, no libm, no malloc, no multiply, no float. */', '',
         '#include "%s"' % MODEL_INC,
         '#include "%s"' % CASES_INC, '']
    L += [KERNEL_BODY]
    open(path, "w").write("\n".join(L) + "\n")
    return len(blob), ncase


def emit(nets, hdr_path, c_path):
    blob, meta = _blob(nets)
    esc = "".join("\\x%02x" % b for b in blob)
    chunks = [esc[i:i + 4 * 20] for i in range(0, len(esc), 4 * 20)]
    h = ['/* generated by `unisa emit-kernel` -- do not edit */',
         '#define NSTAGE %d' % len(meta),
         '#define MODEL_LEN %d' % len(blob), '',
         'char *MODEL =']
    h += ['  "%s"' % c for c in chunks]
    h[-1] += ';'
    h += ['', '/* stage, nfields, nunits, nheads, blob offset */',
          'int STAGE_M[%d];' % len(meta), 'int STAGE_H[%d];' % len(meta),
          'int STAGE_NH[%d];' % len(meta), 'int STAGE_OFF[%d];' % len(meta),
          'int STAGE_NCLS[%d];' % (len(meta) * 12),
          'int STAGE_MW[%d];' % len(meta),
          'int STAGE_VLEN[%d];' % (len(meta) * 4), '',
          'int model_dims(void) {']
    for i, (st, m, H, nh, off, ncls, vlen, mw) in enumerate(meta):
        h.append('  STAGE_M[%d] = %d; STAGE_H[%d] = %d; STAGE_NH[%d] = %d;'
                 ' STAGE_OFF[%d] = %d; STAGE_MW[%d] = %d;   /* %s */'
                 % (i, m, i, H, i, nh, i, off, i, mw, st))
        for k, c in enumerate(ncls):
            h.append('  STAGE_NCLS[%d] = %d;' % (i * 12 + k, c))
        for k, c in enumerate(vlen):
            h.append('  STAGE_VLEN[%d] = %d;' % (i * 4 + k, c))
    h += ['  return %d;' % len(meta), '}']
    open(hdr_path, "w").write("\n".join(h) + "\n")

    open(c_path, "w").write(C_KERNEL)
    return len(blob), len(meta)


KERNEL_BODY = r'''/* the kernel -- the deploy kernel. [K-1] [K-2] [K-5]
 *
 * embed -> match -> add -> argmax.  No softmax, no libm, no malloc, and -- for
 * the constructed integer nets -- no multiply and no float either: a unit fires
 * when every one of its literal masks contains the key's value, and a firing
 * unit simply ADDS its W2 entries.
 *
 * Written in the same C subset unisa itself compiles, so `unisa run` and
 * `cc` must agree on its output.
 */
int getb(int i) { return MODEL[i] & 255; }

long mask64(int p) {
    long v; int k;
    v = 0;
    k = 7;
    while (k >= 0) { v = (v << 8) | getb(p + k); k = k - 1; }
    return v;
}

/* one decision: stage index s, key[] holds one value index per field */
int infer(int s, int *key, int head) {
    int m; int H; int off; int j; int f; int hit; int ne; int k;
    int p; int best; int bi; int u; int hh; int c; int w; int ncls;
    int any; int got; int wi; int mw; int q;
    long lit;
    m = STAGE_M[s]; H = STAGE_H[s]; off = STAGE_OFF[s]; mw = STAGE_MW[s];
    /* a key outside the table is never answered [P-2]: the net is only
       defined on the domain it was verified on.  -1 tells the caller. */
    f = 0;
    while (f < m) {
        if (key[f] < 0 || key[f] >= STAGE_VN[(s << 2) + f]) return 0 - 1;
        f = f + 1;
    }
    /* the masks are stored unit by unit, field by field, word by word --
       the order this loop visits them -- so one running offset reaches
       every one, and no index is multiplied out */
    q = off;
    j = 0;
    while (j < H) {
        hit = 1;
        f = 0;
        while (f < m) {
            /* MASKW u64 words per field: a vocabulary may exceed 64 values */
            any = 0; got = 0; wi = 0;
            while (wi < mw) {
                lit = mask64(q); q = q + 8;
                if (lit) any = 1;
                if (wi == (key[f] >> 6)) {
                    if ((lit >> (key[f] & 63)) & 1) got = 1;
                }
                wi = wi + 1;
            }
            if (any) { if (got == 0) hit = 0; }
            f = f + 1;
        }
        act[j] = hit;
        j = j + 1;
    }
    p = q;
    ne = getb(p) | (getb(p+1) << 8) | (getb(p+2) << 16) | (getb(p+3) << 24);
    p = p + 4;
    ncls = STAGE_NCLS[(s << 3) + (s << 2) + head];
    c = 0;
    while (c < ncls) { z[c] = 0; c = c + 1; }
    k = 0;
    while (k < ne) {
        u = getb(p) | (getb(p+1) << 8);
        hh = getb(p+2);
        c = getb(p+3) | (getb(p+4) << 8);
        w = getb(p+5) | (getb(p+6) << 8);
        if (hh == head) { if (act[u]) z[c] = z[c] + w; }
        p = p + 7;
        k = k + 1;
    }
    best = z[0]; bi = 0;
    c = 1;
    while (c < ncls) { if (z[c] > best) { best = z[c]; bi = c; } c = c + 1; }
    return bi;
}

int main(void) {
    int i; int p; int s; int h; int got; int want; int bad;
    int key[4];
    model_dims();
    bad = 0;
    i = 0;
    p = 0;
    while (i < NCASE) {
        s = CASES[p] & 255;
        h = CASES[p+1] & 255;
        key[0] = CASES[p+2] & 255;
        key[1] = CASES[p+3] & 255;
        key[2] = CASES[p+4] & 255;
        key[3] = CASES[p+5] & 255;
        want = (CASES[p+6] & 255) | ((CASES[p+7] & 255) << 8);
        got = infer(s, key, h);
        if (got != want) bad = bad + 1;
        p = p + 8;
        i = i + 1;
    }
    printf("%d decisions, %d wrong\n", NCASE, bad);
    return bad != 0;
}
'''
