"""Emit the decision layer as C: model data + the integer kernel. [K-5]

The point of the thesis is that deployment is "inferencer + executor + model
data".  This writes exactly that, in C, from the constructed integer nets:

  unisa_model.h  the units as a byte blob plus dimensions
  unisa_boot.c   the kernel (embed -> match -> add -> argmax) and a self-test

The blob avoids nested array initialisers, which our own C subset does not yet
parse -- so the generated C is inside the subset and unisa can compile it.
"""
from .gold import STAGES, ALL


def _blob(nets):
    """unit records, flat: [nf][fieldmasks...][nw2][(unit,cls,w)...]"""
    out = bytearray()
    meta = []
    for st in ALL:
        n = nets[st]
        S = STAGES[st]
        m = len(S.fields)
        start = len(out)
        # per unit: m little-endian u64 literal masks (0 = don't care)
        cols = [[0] * sum(len(v) for (_, v) in S.fields) for _ in range(n.H)]
        for c, us in enumerate(n.feeds):
            for j in us:
                cols[j][c] = 1
        offs, o = [], 0
        for (_, v) in S.fields:
            offs.append(o)
            o += len(v)
        for j in range(n.H):
            for i, (_, v) in enumerate(S.fields):
                mask = 0
                for k in range(len(v)):
                    if cols[j][offs[i] + k]:
                        mask |= 1 << k
                if mask == (1 << len(v)) - 1:
                    mask = 0                      # every value -> don't care
                out += mask.to_bytes(8, "little")
        ents = []
        for hi, (hn, cl) in enumerate(n.heads):
            for j in range(n.H):
                for (k, w) in n.w2[hn][j]:
                    ents.append((j, hi, k, w))
        out += len(ents).to_bytes(4, "little")
        for (j, hi, k, w) in ents:
            out += bytes([j & 0xFF, (j >> 8) & 0xFF, hi, k & 0xFF,
                          (k >> 8) & 0xFF, w])
        meta.append((st, m, n.H, len(n.heads), start,
                     [len(cl) for _, cl in n.heads],
                     [len(v) for (_, v) in S.fields]))
    return bytes(out), meta


def _cases(nets):
    """Every key of every stage, with the expected class index per head."""
    out = bytearray()
    n = 0
    for si, st in enumerate(ALL):
        S = STAGES[st]
        net = nets[st]
        vidx = [{v: i for i, v in enumerate(vo)} for (_, vo) in S.fields]
        hidx = [{c: i for i, c in enumerate(cl)} for _, cl in net.heads]
        for kv in S.keys():
            lab = S.label(*kv)
            for hi, (hn, cl) in enumerate(net.heads):
                out += bytes([si, hi])
                for i in range(4):
                    out += bytes([vidx[i][kv[i]] if i < len(kv) else 0])
                e = hidx[hi][lab[hn]]
                out += bytes([e & 0xFF, (e >> 8) & 0xFF])
                n += 1
    return bytes(out), n


def _cstr(b, name):
    esc = "".join("\\x%02x" % x for x in b)
    ch = [esc[i:i + 80] for i in range(0, len(esc), 80)]
    return ["char *%s =" % name] + ['  "%s"' % c for c in ch[:-1]] + \
        ['  "%s";' % ch[-1]]


def emit_core(nets, path):
    """model + dims + kernel, no main -- the reusable half. [K-5]"""
    blob, meta = _blob(nets)
    L = ['/* generated by `unisa emit-kernel` -- do not edit.',
         ' * The decision layer as C: model data + the integer kernel [K-5].',
         ' * No softmax, no libm, no malloc, no multiply, no float. */', '']
    for i, (st, m, H, nh, off, ncls, vlen) in enumerate(meta):
        L.append('#define S_%s %d' % (st.upper(), i))
    L += ['']
    L += _cstr(blob, "MODEL")
    L += ['', '#define NSTAGE %d' % len(meta), '']
    L += ['int STAGE_M[%d];' % len(meta), 'int STAGE_H[%d];' % len(meta),
          'int STAGE_OFF[%d];' % len(meta),
          'int STAGE_NCLS[%d];' % (len(meta) * 12),
          'int act[4096];', 'int z[512];', '']
    L += ['int model_dims(void) {']
    for i, (st, m, H, nh, off, ncls, vlen) in enumerate(meta):
        L.append('  STAGE_M[%d] = %d; STAGE_H[%d] = %d; STAGE_OFF[%d] = %d;'
                 % (i, m, i, H, i, off))
        for k, c in enumerate(ncls):
            L.append('  STAGE_NCLS[%d] = %d;' % (i * 12 + k, c))
    L += ['  return %d;' % len(meta), '}', '']
    # vocabularies the C side needs, packed as NUL-separated strings so no
    # array-of-pointer initialiser is required (our subset has none yet)
    from .gold import TOKS, PRODS, LEXACT, DIRS, PPACT, NT
    from .front.lex import TYPEKW
    for nm, vals in (("TOKV", TOKS), ("PRODV", PRODS), ("ACTV", LEXACT),
                     ("TYPEV", TYPEKW), ("DIRV", DIRS), ("PPACTV", PPACT),
                     ("NTV", NT)):
        packed = "".join(v + "\\0" for v in vals)
        L += ['char *%s = "%s";' % (nm, packed),
              '#define N%s %d' % (nm, len(vals)), '']
    L += [KERNEL_BODY.split('int main(void)')[0]]
    open(path, "w").write("\n".join(L) + "\n")
    return len(blob), len(meta)


def emit_self(nets, path):
    """One self-contained C file: model + kernel + full-gold self test.
    Self-contained because our own `#include` is a no-op, so the generated C
    has to be compilable by unisa as well as by cc."""
    blob, meta = _blob(nets)
    cases, ncase = _cases(nets)
    L = ['/* generated by `unisa emit-kernel` -- do not edit.',
         ' * The decision layer as C: model data + the integer kernel [K-5],',
         ' * self-testing over the FULL gold corpus [P-3].',
         ' * No softmax, no libm, no malloc, no multiply, no float. */', '']
    L += _cstr(blob, "MODEL")
    L += ['']
    L += _cstr(cases, "CASES")
    L += ['', '#define NSTAGE %d' % len(meta), '#define NCASE %d' % ncase, '']
    L += ['int STAGE_M[%d];' % len(meta), 'int STAGE_H[%d];' % len(meta),
          'int STAGE_OFF[%d];' % len(meta),
          'int STAGE_NCLS[%d];' % (len(meta) * 12),
          'int act[4096];', 'int z[512];', '']
    L += ['int model_dims(void) {']
    for i, (st, m, H, nh, off, ncls, vlen) in enumerate(meta):
        L.append('  STAGE_M[%d] = %d; STAGE_H[%d] = %d; STAGE_OFF[%d] = %d;'
                 % (i, m, i, H, i, off))
        for k, c in enumerate(ncls):
            L.append('  STAGE_NCLS[%d] = %d;' % (i * 12 + k, c))
    L += ['  return %d;' % len(meta), '}', '']
    L += [KERNEL_BODY]
    open(path, "w").write("\n".join(L) + "\n")
    return len(blob), ncase


def emit(nets, hdr_path, c_path):
    blob, meta = _blob(nets)
    esc = "".join("\\x%02x" % b for b in blob)
    chunks = [esc[i:i + 4 * 20] for i in range(0, len(esc), 4 * 20)]
    h = ['/* generated by `unisa emit-kernel` -- do not edit */',
         '#define NSTAGE %d' % len(meta),
         '#define MODEL_LEN %d' % len(blob), '',
         'char *MODEL =']
    h += ['  "%s"' % c for c in chunks]
    h[-1] += ';'
    h += ['', '/* stage, nfields, nunits, nheads, blob offset */',
          'int STAGE_M[%d];' % len(meta), 'int STAGE_H[%d];' % len(meta),
          'int STAGE_NH[%d];' % len(meta), 'int STAGE_OFF[%d];' % len(meta),
          'int STAGE_NCLS[%d];' % (len(meta) * 12),
          'int STAGE_VLEN[%d];' % (len(meta) * 4), '',
          'int model_dims(void) {']
    for i, (st, m, H, nh, off, ncls, vlen) in enumerate(meta):
        h.append('  STAGE_M[%d] = %d; STAGE_H[%d] = %d; STAGE_NH[%d] = %d;'
                 ' STAGE_OFF[%d] = %d;   /* %s */' % (i, m, i, H, i, nh, i,
                                                      off, st))
        for k, c in enumerate(ncls):
            h.append('  STAGE_NCLS[%d] = %d;' % (i * 12 + k, c))
        for k, c in enumerate(vlen):
            h.append('  STAGE_VLEN[%d] = %d;' % (i * 4 + k, c))
    h += ['  return %d;' % len(meta), '}']
    open(hdr_path, "w").write("\n".join(h) + "\n")

    open(c_path, "w").write(C_KERNEL)
    return len(blob), len(meta)


KERNEL_BODY = r'''/* the kernel -- the deploy kernel. [K-1] [K-2] [K-5]
 *
 * embed -> match -> add -> argmax.  No softmax, no libm, no malloc, and -- for
 * the constructed integer nets -- no multiply and no float either: a unit fires
 * when every one of its literal masks contains the key's value, and a firing
 * unit simply ADDS its W2 entries.
 *
 * Written in the same C subset unisa itself compiles, so `unisa run` and
 * `cc` must agree on its output.
 */
int getb(int i) { return MODEL[i] & 255; }

long mask64(int p) {
    long v; int k;
    v = 0;
    k = 7;
    while (k >= 0) { v = (v << 8) | getb(p + k); k = k - 1; }
    return v;
}

/* one decision: stage index s, key[] holds one value index per field */
int infer(int s, int *key, int head) {
    int m; int H; int off; int j; int f; int hit; int ne; int k;
    int p; int best; int bi; int u; int hh; int c; int w; int ncls;
    long lit;
    m = STAGE_M[s]; H = STAGE_H[s]; off = STAGE_OFF[s];
    j = 0;
    while (j < H) {
        hit = 1;
        f = 0;
        while (f < m) {
            lit = mask64(off + (j * m + f) * 8);
            if (lit) { if (((lit >> key[f]) & 1) == 0) hit = 0; }
            f = f + 1;
        }
        act[j] = hit;
        j = j + 1;
    }
    p = off + H * m * 8;
    ne = getb(p) | (getb(p+1) << 8) | (getb(p+2) << 16) | (getb(p+3) << 24);
    p = p + 4;
    ncls = STAGE_NCLS[s * 12 + head];
    c = 0;
    while (c < ncls) { z[c] = 0; c = c + 1; }
    k = 0;
    while (k < ne) {
        u = getb(p) | (getb(p+1) << 8);
        hh = getb(p+2);
        c = getb(p+3) | (getb(p+4) << 8);
        w = getb(p+5);
        if (hh == head) { if (act[u]) z[c] = z[c] + w; }
        p = p + 6;
        k = k + 1;
    }
    best = z[0]; bi = 0;
    c = 1;
    while (c < ncls) { if (z[c] > best) { best = z[c]; bi = c; } c = c + 1; }
    return bi;
}

int main(void) {
    int i; int p; int s; int h; int got; int want; int bad;
    int key[4];
    model_dims();
    bad = 0;
    i = 0;
    p = 0;
    while (i < NCASE) {
        s = CASES[p] & 255;
        h = CASES[p+1] & 255;
        key[0] = CASES[p+2] & 255;
        key[1] = CASES[p+3] & 255;
        key[2] = CASES[p+4] & 255;
        key[3] = CASES[p+5] & 255;
        want = (CASES[p+6] & 255) | ((CASES[p+7] & 255) << 8);
        got = infer(s, key, h);
        if (got != want) bad = bad + 1;
        p = p + 8;
        i = i + 1;
    }
    printf("%d decisions, %d wrong\n", NCASE, bad);
    return bad != 0;
}
'''
