"""The stage table, generated -- so the documents cannot fall behind. [A-48]

The table of stages (rows, units, key fields, outputs) used to be copied by
hand into four files.  After the 11 -> 14 stage refactor, `prd.tree.md` and
`prd.map.md` went on describing the eleven-stage compiler for a day, and
nothing noticed, because nothing compared them with anything.

Now the table is generated from the one place that knows -- `unisa/gold.py`
and the constructed weights -- and written between markers:

    <!-- stages:begin -->  ...  <!-- stages:end -->

`python3 -m unisa docs` rewrites every marked region; `--check` reports
the files whose region differs and exits 1, which is what tests/docs.sh
runs.  Text outside the markers is never touched: the prose around a table
is a person's, the table is the code's.
"""
import os
import re
import sys

BEGIN = "<!-- stages:begin -->"
END = "<!-- stages:end -->"
# Files that carry the table.  prd.md is the spec and keeps its own
# annotated copy; these are the restatements that drifted.
FILES = ("prd.tree.md", "prd.map.md", "README.md")


def rows():
    """(stage, key fields, outputs, keys, units, acc) for every stage, from
    the gold tables and the constructed weights -- never typed."""
    from .gold import STAGES, ALL
    from .__main__ import _built
    nets = _built()
    out = []
    for n in ALL:
        st = STAGES[n]
        fields = " x ".join("%s(%d)" % (f, len(v)) for f, v in st.fields)
        heads = getattr(st, "heads", None) or []
        if len(heads) > 1:
            outs = "%d heads" % len(heads)
        elif heads:
            outs = "%d classes" % len(heads[0][1])
        else:
            outs = "-"
        out.append((n, fields, outs, st.rows(), nets[n].nunits()))
    return out


def table():
    R = rows()
    L = ["| stage | key | out | keys | units |",
         "|---|---|---|---:|---:|"]
    for n, fields, outs, k, u in R:
        L.append("| `%s` | %s | %s | %s | %d |" % (n, fields, outs, format(k, ","), u))
    L.append("| **total** | | | **%s** | **%d** |"
             % (format(sum(r[3] for r in R), ","), sum(r[4] for r in R)))
    L.append("")
    L.append("*Generated by `python3 -m unisa docs` from `unisa/gold.py` and the "
             "constructed weights; `tests/docs.sh` fails when this differs.*")
    return "\n".join(L)


def rewrite(text, block):
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(text):
        return None
    return pat.sub(BEGIN + "\n" + block + "\n" + END, text)


def main(argv, root):
    check = "--check" in argv
    block = table()
    bad = []
    for f in FILES:
        p = os.path.join(root, f)
        if not os.path.exists(p):
            continue
        t = open(p, encoding="utf-8").read()
        new = rewrite(t, block)
        if new is None:
            bad.append("%s: no %s ... %s markers" % (f, BEGIN, END))
            continue
        if new != t:
            if check:
                bad.append("%s: the stage table is out of date" % f)
            else:
                open(p, "w", encoding="utf-8").write(new)
                print("  rewrote %s" % f)
    for b in bad:
        print("  " + b)
    return 1 if (bad and check) else 0
