"""The stage table, generated -- so the documents cannot fall behind. [A-48]

The table of stages (rows, units, key fields, outputs) used to be copied by
hand into four files.  After the 11 -> 14 stage refactor, `prd.tree.md` and
`prd.map.md` went on describing the eleven-stage compiler for a day, and
nothing noticed, because nothing compared them with anything.

Now the table is generated from the one place that knows -- `unisa/gold.py`
and the constructed weights -- and written between markers:

    <!-- stages:begin -->  ...  <!-- stages:end -->

`python3 -m unisa docs` rewrites every marked region; `--check` reports
the files whose region differs and exits 1, which is what tests/docs.sh
runs.  Text outside the markers is never touched: the prose around a table
is a person's, the table is the code's.
"""
import os
import re
import sys

BEGIN = "<!-- stages:begin -->"
END = "<!-- stages:end -->"
# Files that carry the table.  prd.md is the spec and keeps its own
# annotated copy; these are the restatements that drifted.
FILES = ("prd.tree.md", "prd.map.md", "README.md")


def rows():
    """(stage, key fields, outputs, keys, units, acc) for every stage, from
    the gold tables and the constructed weights -- never typed."""
    from .gold import STAGES, ALL
    from .__main__ import _built
    nets = _built()
    out = []
    for n in ALL:
        st = STAGES[n]
        fields = " x ".join("%s(%d)" % (f, len(v)) for f, v in st.fields)
        heads = getattr(st, "heads", None) or []
        if len(heads) > 1:
            outs = "%d heads" % len(heads)
        elif heads:
            outs = "%d classes" % len(heads[0][1])
        else:
            outs = "-"
        out.append((n, fields, outs, st.rows(), nets[n].nunits()))
    return out


def table():
    R = rows()
    L = ["| stage | key | out | keys | units |",
         "|---|---|---|---:|---:|"]
    for n, fields, outs, k, u in R:
        L.append("| `%s` | %s | %s | %s | %d |" % (n, fields, outs, format(k, ","), u))
    L.append("| **total** | | | **%s** | **%d** |"
             % (format(sum(r[3] for r in R), ","), sum(r[4] for r in R)))
    L.append("")
    L.append("*Generated by `python3 -m unisa docs` from `unisa/gold.py` and the "
             "constructed weights; `tests/docs.sh` fails when this differs.*")
    return "\n".join(L)


def rewrite(text, block, begin=BEGIN, end=END):
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if not pat.search(text):
        return None
    return pat.sub(lambda m: begin + "\n" + block + "\n" + end, text)


# ---- the paper's table 1, in Chinese, with the accuracy column [E2] -----
ZH_BEGIN = "<!-- stages-zh:begin -->"
ZH_END = "<!-- stages-zh:end -->"
PAPER = os.path.join("research", "unisacc-paper.md")
ZH_FIELD = {"dir": "指令", "defined": "已定义", "c": "字符类", "peek": "前瞻",
            "nt": "非终结符", "tok": "记号", "t1": "类型", "t2": "类型",
            "op": "操作", "ctx": "上下文", "kind": "种类", "family": "族",
            "flavor": "变体", "os": "OS", "arch": "架构", "treg": "tape 寄存器",
            "t": "类型", "conv": "转换符", "a": "指令 A", "b": "指令 B",
            "rel": "关系"}


def _acc(nets, n):
    """by enumeration over the FULL gold, ties counted wrong -- as `acc`"""
    from .gold import STAGES
    from .__main__ import _ties
    st = STAGES[n]
    wrong = 0
    for key in st.keys():
        want = st.label(*key)
        got = nets[n].predict(key)
        tie = _ties(nets[n], key)
        for h, _, _ in st.heads:
            if got[h] != want[h] or tie[h]:
                wrong += 1
    return "1.000" if wrong == 0 else "%d 错" % wrong


def table_zh():
    from .gold import STAGES, ALL
    from .__main__ import _built
    nets = _built()
    L = ["| 阶段 | 键字段 × 词表大小 | 输出 | 键数 | 单元 | 精度 |",
         "|---|---|---|---:|---:|---:|"]
    tk = tu = 0
    for n in ALL:
        st = STAGES[n]
        fields = " × ".join("%s %d" % (ZH_FIELD.get(f, f), len(v))
                            for f, v in st.fields)
        hs = st.heads
        outs = "%d 头" % len(hs) if len(hs) > 1 else str(len(hs[0][1]))
        k, u = st.rows(), nets[n].nunits()
        tk += k; tu += u
        L.append("| %s | %s | %s | %s | %d | %s |"
                 % (n, fields, outs, format(k, ","), u, _acc(nets, n)))
    L.append("| **合计** | | | **%s** | **%d** | |" % (format(tk, ","), tu))
    return "\n".join(L)


def main(argv, root):
    check = "--check" in argv
    block = table()
    bad = []
    for f in FILES:
        p = os.path.join(root, f)
        if not os.path.exists(p):
            continue
        t = open(p, encoding="utf-8").read()
        new = rewrite(t, block)
        if new is None:
            bad.append("%s: no %s ... %s markers" % (f, BEGIN, END))
            continue
        if new != t:
            if check:
                bad.append("%s: the stage table is out of date" % f)
            else:
                open(p, "w", encoding="utf-8").write(new)
                print("  rewrote %s" % f)
    p = os.path.join(root, PAPER)
    if os.path.exists(p):
        t = open(p, encoding="utf-8").read()
        new = rewrite(t, table_zh(), ZH_BEGIN, ZH_END)
        if new is None:
            bad.append("%s: no %s ... %s markers" % (PAPER, ZH_BEGIN, ZH_END))
        elif new != t:
            if check:
                bad.append("%s: table 1 is out of date" % PAPER)
            else:
                open(p, "w", encoding="utf-8").write(new)
                print("  rewrote %s" % PAPER)
    for b in bad:
        print("  " + b)
    return 1 if (bad and check) else 0
