/* Numeric ABI for decoded actions; checked against core.h. */
#define OP_ADV 0
#define OP_MARK 1
#define OP_JUMP 2
#define OP_LDI 3
#define OP_COPYW 4
#define OP_ALU 5
#define OP_ALUI 6
#define OP_CMP 7
#define OP_CMPI 8
#define OP_RLD 9
#define OP_LDX 10
#define OP_STX 11
#define OP_OUT 12
#define OP_OUTW 13
#define OP_COPY 14
#define OP_COPYT 15
#define OP_SPAN 16
#define OP_SPANT 17
#define OP_SPAN2 18
#define OP_OLAST 19
#define OP_ODROP 20
#define OP_OLEN 21
#define OP_OCUT 22
#define OP_ORES 23
#define OP_OFILL 24
#define OP_OCLR 25
#define OP_OSEL 26
#define OP_SETOT 27
#define OP_XATTR 28
#define OP_PUSH 29
#define OP_POP 30
#define OP_INTERN 31
#define OP_BLOBSAVE 32
#define OP_INPUSH 33
#define OP_INPUSHX 34
#define OP_INPUSHXE 35
#define OP_INPOP 36
#define OP_SBCLR 37
#define OP_SBOUT 38
#define OP_SBSPAN 39
#define OP_SBBLOB 40
#define OP_SBINTERN 41
#define OP_SBSAVE 42
#define OP_SBFIND 43
#define OP_BLEN 44
#define OP_BYTE 45
#define OP_XLEN 46
#define OP_DIVMOD10 47
#define OP_SWAP 48
#define OP_ACCEPT 49
#define OP_REJECT 50
#define OP_A64 51
#define OP_A64I 52
#define OP_C64 53
#define OP_C64U 54
#define OP_INC 55
#define OP_COUNT 56
