"""Library public roots from complete USLSIG1/2 framing, interpreted in delta."""
SEEN, ROOT = (i<<40 for i in (80,81))
def install(E,P,B,limit):
    from pathlib import Path
    schema=dict(line.split("\t") for line in (Path(__file__).with_name("libraryroots-schema.tsv")).read_text().splitlines() if line and not line.startswith("#"))
    magic=bytes.fromhex(schema["magic"]);widths=tuple(map(int,schema["widths"].split(",")))
    assert magic==b"USLSIG1\n" and bytes.fromhex(schema["magic-v2"])==b"USLSIG2\n"
    assert set(schema)=={"magic","magic-v2","class-max","widths","flag-max","stored-max","parameter-max-v2","extent-max-v2","alignment-max-v2"}
    assert widths==(0,1,2,4,8) and int(schema["class-max"])==6 and int(schema["flag-max"])==1 and int(schema["stored-max"])==8
    params_max=int(schema["parameter-max-v2"]);extent_max=int(schema["extent-max-v2"]);alignment_max=int(schema["alignment-max-v2"])
    assert (params_max,extent_max,alignment_max)==(1024,16777216,65536)
    from modelsignature import install as signature_install
    signature_install(E,fail="LR.bad")
    g=E.g
    def test(p,x,y,yes,no):p.branch({1:yes},no,[("CMPI",x,y)])
    def hook(name,proc):
        old="LR.original."+name;g.st[old]=g.st.pop(name);g.labels.add(old)
        P(name).a(("PUSH",old)).goto(proc)
    hook("START","LR.resource")
    P("LR.resource").a(("LDI","lr_zero",0),("LDI","lr_count",0),("SBCLR",),
        [("SBOUT",c) for c in b"\0library/signatures"],("SBFIND","lr_blob")).branch({1:"LR.return"},"LR.open",[("CMPI","lr_blob",0)])
    P("LR.return").ret()
    P("LR.bad").a(E.rej("not covered: malformed library signatures or missing public label")).goto("DEAD")
    P("LR.open").a(("INPUSH","lr_blob"),("XLEN","lr_len")).goto("LR.magic0")
    for i,c in enumerate(magic[:6]):
        P("LR.magic"+str(i)).branch({c:"LR.magicadv"+str(i)},"LR.bad",[("BYTE","lr_c"),("RLD","lr_c")])
        P("LR.magicadv"+str(i)).a(("ADV",)).goto("LR.magic"+str(i+1))
    P("LR.magic6").branch({49:"LR.version1",50:"LR.version2"},"LR.bad",[("BYTE","lr_c"),("RLD","lr_c")])
    P("LR.version1").a(("LDI","lr_version",1),("ADV",)).goto("LR.magic7")
    P("LR.version2").a(("LDI","lr_version",2),("ADV",),("LDI","lr_limit",extent_max)).branch({2:"LR.bad"},"LR.magic7",[("C64U","lr_len","lr_limit")])
    P("LR.magic7").branch({10:"LR.magicadv7"},"LR.bad",[("BYTE","lr_c"),("RLD","lr_c")])
    P("LR.magicadv7").a(("ADV",)).goto("LR.count")
    P("LR.count").call("LR.u64").a(("COPYW","lr_records","lr_value"),("LDI","lr_limit",limit)).branch({2:"LR.bad"},"LR.begin",[("C64U","lr_records","lr_limit")])
    P("LR.begin").a(("LDI","lr_rec",0)).goto("LR.loop")
    P("LR.loop").branch({1:"LR.end"},"LR.name",[("CMP","lr_rec","lr_records")])
    P("LR.name").call("LR.u64").a(("COPYW","lr_n","lr_value"),("MARK","lr_s"),("A64","sub","lr_left","lr_len","lr_s")).branch({2:"LR.bad"},"LR.nonempty",[("C64U","lr_n","lr_left")])
    test(P("LR.nonempty"),"lr_n",0,"LR.bad","LR.namebegin")
    P("LR.namebegin").a(("A64","add","lr_e","lr_s","lr_n")).goto("LR.first")
    letters=tuple(range(65,91))+tuple(range(97,123))+(95,)
    def byte(name,good,yes,no):
        g.on(name,good,yes,[],"b");g.on(name,[x for x in range(257) if x not in good],no,[],"b")
    byte("LR.first",letters,"LR.nameadv","LR.bad")
    P("LR.nameadv").a(("ADV",),("MARK","lr_pos")).branch({1:"LR.nameend"},"LR.tail",[("CMP","lr_pos","lr_e")])
    byte("LR.tail",letters+tuple(range(48,58))+(46,36),"LR.nameadv","LR.bad")
    P("LR.nameend").a(("INTERN","lr_id","lr_s","lr_e"),("JUMP","lr_e"),("LDX","lr_seen","lr_id",SEEN)).branch({1:"LR.link"},"LR.bad",[("CMPI","lr_seen",0)])
    P("LR.link").a(("LDI","lr_one",1),("STX","lr_id",SEEN,"lr_one")).call("LR.bit").a(("COPYW","lr_link","lr_value")).call("LR.bit").branch({1:"LR.var"},"LR.bad",[("CMPI","lr_value",1)])
    P("LR.var").call("LR.bit").a(("COPYW","lr_variadic","lr_value")).branch({1:"LR.v1params"},"LR.mode",[("CMPI","lr_version",1)])
    P("LR.v1params").call("LR.u64").a(("COPYW","lr_params","lr_value")).goto("LR.result")
    P("LR.mode").call("LR.bit").a(("COPYW","lr_mode","lr_value")).call("LR.u64").a(("COPYW","lr_params","lr_value"),("LDI","lr_limit",params_max)).branch({2:"LR.bad"},"LR.modevar",[("C64U","lr_params","lr_limit")])
    P("LR.modevar").branch({1:"LR.stackmode"},"LR.modecount",[("CMPI","lr_variadic",1)])
    P("LR.modecount").a(("LDI","lr_limit",6)).branch({2:"LR.stackmode"},"LR.registermode",[("C64U","lr_params","lr_limit")])
    test(P("LR.stackmode"),"lr_mode",1,"LR.result","LR.bad")
    test(P("LR.registermode"),"lr_mode",0,"LR.result","LR.bad")
    P("LR.result").a(("LDI","ms_level",0),("LDI","ms_nodes",0),("LDI","ms_signatures",0),("LDI","ms_callbacks",0)).call("LR.desc").call("LR.u64").a(("COPYW","lr_stored","lr_value")).branch({1:"LR.v1stored"},"LR.same",[("CMPI","lr_version",1)])
    P("LR.v1stored").a(("LDI","lr_limit",8)).branch({2:"LR.eight"},"LR.same",[("C64U","lr_params","lr_limit")])
    P("LR.eight").a(("LDI","lr_expected",8)).goto("LR.stored")
    P("LR.same").a(("COPYW","lr_expected","lr_params")).goto("LR.stored")
    P("LR.stored").branch({1:"LR.paramstart"},"LR.bad",[("CMP","lr_stored","lr_expected")])
    P("LR.paramstart").a(("LDI","lr_pi",0)).goto("LR.paramloop")
    P("LR.paramloop").branch({1:"LR.supported"},"LR.param",[("CMP","lr_pi","lr_stored")])
    P("LR.param").call("LR.desc").a(("ALUI","add","lr_pi","lr_pi",1)).goto("LR.paramloop")
    P("LR.supported").call("LR.bit").a(("COPYW","lr_support","lr_value")).branch({1:"LR.supportlegacy"},"LR.supportgraph",[("CMPI","lr_version",1)])
    test(P("LR.supportgraph"),"ms_callbacks",0,"LR.supportlegacy","LR.supportzero")
    test(P("LR.supportzero"),"lr_support",0,"LR.supportlegacy","LR.bad")
    P("LR.supportlegacy").branch({1:"LR.save"},"LR.next",[("CMPI","lr_link",0)])
    P("LR.save").a(("STX","lr_count",ROOT,"lr_id"),("ALUI","add","lr_count","lr_count",1)).goto("LR.next")
    P("LR.next").a(("ALUI","add","lr_rec","lr_rec",1)).goto("LR.loop")
    P("LR.end").a(("MARK","lr_pos")).branch({1:"LR.done"},"LR.bad",[("CMP","lr_pos","lr_len")])
    P("LR.done").a(("INPOP",)).ret()
    # Complete six-field descriptors; opaque depth/base/shape preserved, not guessed.
    P("LR.desc").branch({1:"LR.desc1"},"LR.desc2",[("CMPI","lr_version",1)])
    P("LR.desc1").call("LR.u64").call("LR.u64").call("LR.u64").call("LR.u64").a(("LDI","lr_limit",int(schema["class-max"]))).branch({2:"LR.bad"},"LR.width",[("C64U","lr_value","lr_limit")])
    P("LR.width").call("LR.u64").branch({widths:"LR.unsigned"},"LR.bad",[("RLD","lr_value")])
    P("LR.unsigned").call("LR.u64").a(("LDI","lr_limit",1)).branch({2:"LR.bad"},"LR.return",[("C64U","lr_value","lr_limit")])
    # Share the complete graph validator across result and all parameters.
    # Canonical bytes are private scratch; prune retains public roots by linkage.
    P("LR.desc2").a(("COPYW","ms_limit","lr_len"),("OLEN","lr_canoncut")).call("MS.desc").a(("OCUT","lr_canon","lr_canoncut")).ret()
    P("LR.bit").a(("BYTE","lr_value"),("ADV",)).branch({(0,1):"LR.return"},"LR.bad",[("RLD","lr_value")])
    P("LR.u64").a(("MARK","lr_pos"),("A64","sub","lr_left","lr_len","lr_pos"),("LDI","lr_limit",8)).branch({0:"LR.bad"},"LR.u64read",[("C64U","lr_left","lr_limit")])
    P("LR.u64read").a(("LDI","lr_value",0),*[a for i in range(8) for a in [("BYTE","lr_byte"),("A64I","shl","lr_byte","lr_byte",i*8),("A64","or","lr_value","lr_value","lr_byte"),("ADV",)]]).ret()
    hook("QUEUEST","LR.roots")
    P("LR.roots").a(("LDI","lr_i",0)).goto("LR.rootloop")
    P("LR.rootloop").branch({1:"LR.return"},"LR.root",[("CMP","lr_i","lr_count")])
    P("LR.root").a(("LDX","lr_id","lr_i",ROOT),("LDX","lr_label","lr_id",B['LAB'])).branch({1:"LR.bad"},"LR.rootmark",[("CMPI","lr_label",0)])
    P("LR.rootmark").a(("ALUI","sub","lr_label","lr_label",1),("LDX","lr_unit","lr_label",B['OWNER']),("LDI","lr_one",1),("STX","lr_unit",B['ROOTS'],"lr_one"),("ALUI","add","lr_i","lr_i",1)).goto("LR.rootloop")
