/* <errno.h> for the unisa C subset.  `errno` is an ordinary int in the
 * image: the library functions here set it where C says they must, and the
 * headers that wrap system calls turn a failed call's result into errno.
 * The values are the TARGET kernel's (a raw system call returns them), so
 * they differ by OS: Linux (asm-generic, both architectures) and macOS.
 * 0.0.19: the full POSIX set (dsh 2026-10-01: EINTR et al. were missing). */
#ifndef _UNISA_ERRNO_H
#define _UNISA_ERRNO_H
static int errno = 0;
#ifdef __APPLE__
#define EPERM            1
#define ENOENT           2
#define ESRCH            3
#define EINTR            4
#define EIO              5
#define ENXIO            6
#define E2BIG            7
#define ENOEXEC          8
#define EBADF            9
#define ECHILD           10
#define EAGAIN           35
#define ENOMEM           12
#define EACCES           13
#define EFAULT           14
#define ENOTBLK          15
#define EBUSY            16
#define EEXIST           17
#define EXDEV            18
#define ENODEV           19
#define ENOTDIR          20
#define EISDIR           21
#define EINVAL           22
#define ENFILE           23
#define EMFILE           24
#define ENOTTY           25
#define ETXTBSY          26
#define EFBIG            27
#define ENOSPC           28
#define ESPIPE           29
#define EROFS            30
#define EMLINK           31
#define EPIPE            32
#define EDOM             33
#define ERANGE           34
#define EDEADLK          11
#define ENAMETOOLONG     63
#define ENOLCK           77
#define ENOSYS           78
#define ENOTEMPTY        66
#define ELOOP            62
#define ENOMSG           91
#define EIDRM            90
#define ENOSTR           99
#define ENODATA          96
#define ETIME            101
#define ENOSR            98
#define ENOLINK          97
#define EPROTO           100
#define EMULTIHOP        95
#define EBADMSG          94
#define EOVERFLOW        84
#define EILSEQ           92
#define ENOTSOCK         38
#define EDESTADDRREQ     39
#define EMSGSIZE         40
#define EPROTOTYPE       41
#define ENOPROTOOPT      42
#define EPROTONOSUPPORT  43
#define EOPNOTSUPP       102
#define EAFNOSUPPORT     47
#define EADDRINUSE       48
#define EADDRNOTAVAIL    49
#define ENETDOWN         50
#define ENETUNREACH      51
#define ENETRESET        52
#define ECONNABORTED     53
#define ECONNRESET       54
#define ENOBUFS          55
#define EISCONN          56
#define ENOTCONN         57
#define ETIMEDOUT        60
#define ECONNREFUSED     61
#define EHOSTUNREACH     65
#define EALREADY         37
#define EINPROGRESS      36
#define ESTALE           70
#define EDQUOT           69
#define ECANCELED        89
#define EOWNERDEAD       105
#define ENOTRECOVERABLE  104
#define EWOULDBLOCK      EAGAIN
#define ENOTSUP          45
#else
#define EPERM            1
#define ENOENT           2
#define ESRCH            3
#define EINTR            4
#define EIO              5
#define ENXIO            6
#define E2BIG            7
#define ENOEXEC          8
#define EBADF            9
#define ECHILD           10
#define EAGAIN           11
#define ENOMEM           12
#define EACCES           13
#define EFAULT           14
#define ENOTBLK          15
#define EBUSY            16
#define EEXIST           17
#define EXDEV            18
#define ENODEV           19
#define ENOTDIR          20
#define EISDIR           21
#define EINVAL           22
#define ENFILE           23
#define EMFILE           24
#define ENOTTY           25
#define ETXTBSY          26
#define EFBIG            27
#define ENOSPC           28
#define ESPIPE           29
#define EROFS            30
#define EMLINK           31
#define EPIPE            32
#define EDOM             33
#define ERANGE           34
#define EDEADLK          35
#define ENAMETOOLONG     36
#define ENOLCK           37
#define ENOSYS           38
#define ENOTEMPTY        39
#define ELOOP            40
#define ENOMSG           42
#define EIDRM            43
#define ENOSTR           60
#define ENODATA          61
#define ETIME            62
#define ENOSR            63
#define ENOLINK          67
#define EPROTO           71
#define EMULTIHOP        72
#define EBADMSG          74
#define EOVERFLOW        75
#define EILSEQ           84
#define ENOTSOCK         88
#define EDESTADDRREQ     89
#define EMSGSIZE         90
#define EPROTOTYPE       91
#define ENOPROTOOPT      92
#define EPROTONOSUPPORT  93
#define EOPNOTSUPP       95
#define EAFNOSUPPORT     97
#define EADDRINUSE       98
#define EADDRNOTAVAIL    99
#define ENETDOWN         100
#define ENETUNREACH      101
#define ENETRESET        102
#define ECONNABORTED     103
#define ECONNRESET       104
#define ENOBUFS          105
#define EISCONN          106
#define ENOTCONN         107
#define ETIMEDOUT        110
#define ECONNREFUSED     111
#define EHOSTUNREACH     113
#define EALREADY         114
#define EINPROGRESS      115
#define ESTALE           116
#define EDQUOT           122
#define ECANCELED        125
#define EOWNERDEAD       130
#define ENOTRECOVERABLE  131
#define EWOULDBLOCK      EAGAIN
#define ENOTSUP          EOPNOTSUPP
#define EDEADLOCK        EDEADLK
#endif
#endif
