#!/bin/sh
# fwrite, SIMULATED: tests the CURRENT fwrite function body from
# include/stdio.h, as compiled by each front end (native executable, -run,
# Python --drive built), against a scripted __write shim.
#
# What this is NOT: a test of macro-expansion consistency.  sim.c tried to
# swap __write with `#define __write shim` before `#include <stdio.h>`; the
# native preprocessor does not expand that macro inside the embedded
# header's bodies (README, "known gap"), so natively the shim was never
# called.  Here the substitution is TEXTUAL, done by this script on an
# extracted copy, so every front end compiles the same shimmed body.
#
# Extraction: the `static long fwrite(` definition, through its matching
# closing brace (brace depth counted by awk), is cut from the header -- no
# second copy of the algorithm is kept anywhere.  In that copy only, the
# function is renamed fwrite_under_test and its single `__write(` call
# becomes `shim(`.  The real embedded fwrite/__write stay untouched and
# carry the probe's own printf output, so output never reaches the shim.
#
# usage: tests/fwrite/sim.sh [ref-compiler] [stdio.h]
#   defaults: /tmp/ua_ref, include/stdio.h.  Point the second argument at a
#   temp copy to check that a broken fwrite is caught.
UA=${1:-/tmp/ua_ref}
D=$(cd "$(dirname "$0")" && pwd); R=$(cd "$D/../.." && pwd)
H=${2:-$R/include/stdio.h}
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
b() { perl -e 'alarm shift; exec @ARGV' "$@"; }

awk '
  !on && /^static long fwrite\(/ { on = 1 }
  on {
    print
    t = $0; o = gsub(/\{/, "", t); t = $0; c = gsub(/\}/, "", t)
    depth += o - c; if (o) seen = 1
    if (seen && depth == 0) exit
  }' "$H" > "$T/body.c"
[ -s "$T/body.c" ] || { echo "FAIL extract: no fwrite definition in $H"; exit 1; }
[ "$(grep -c '__write(' "$T/body.c")" = 1 ] || { echo "FAIL extract: expected exactly one __write( call"; exit 1; }
tail -1 "$T/body.c" | grep -q '^}' || { echo "FAIL extract: no closing brace"; exit 1; }
sed -e 's/^static long fwrite(/static long fwrite_under_test(/' \
    -e 's/__write(/shim(/' "$T/body.c" > "$T/body2.c"
grep -q '^static long fwrite_under_test(' "$T/body2.c" || { echo "FAIL extract: rename"; exit 1; }
echo "SIMULATED: extracted $(wc -l < "$T/body.c" | tr -d ' ') lines of fwrite from $H"

{ cat <<'C1'
/* GENERATED by tests/fwrite/sim.sh -- SIMULATED fwrite probe. */
#include <stdio.h>
static char buf[64];
static long ans[8];      /* scripted answers; 99999 = "all of it" */
static long c_off[8];    /* per call: offset of p from buf */
static long c_n[8];      /* per call: requested n */
static long c_ret[8];    /* per call: what the shim returned */
static long calls;
static int fails;
static long shim(int fd, char *p, long n) {
    long r;
    if (calls >= 8) return 0 - 1;      /* runaway loop: force an error */
    r = ans[calls];
    if (r == 99999) r = n;
    c_off[calls] = p - buf; c_n[calls] = n; c_ret[calls] = r;
    calls = calls + 1;
    return r;
}
C1
cat "$T/body2.c"
cat <<'C2'
static void set(long a, long b, long c) {
    long i;
    ans[0] = a; ans[1] = b; ans[2] = c;
    for (i = 3; i < 8; i++) ans[i] = 99999;
    for (i = 0; i < 8; i++) { c_off[i] = 0 - 1; c_n[i] = 0 - 1; c_ret[i] = 0 - 1; }
    calls = 0;
}
/* want: result, call count, then (offset, n, ret) for up to 2 calls */
static void check(char *name, long got, long want, long wc,
                  long o1, long n1, long r1, long o2, long n2, long r2) {
    int bad; long i;
    bad = got != want || calls != wc;
    if (wc >= 1 && !bad) bad = c_off[0] != o1 || c_n[0] != n1 || c_ret[0] != r1;
    if (wc >= 2 && !bad) bad = c_off[1] != o2 || c_n[1] != n2 || c_ret[1] != r2;
    if (bad) fails = fails + 1;
    if (bad) printf("FAIL "); else printf("PASS ");
    printf("%s ret=%ld want=%ld calls=%ld want=%ld", name, got, want, calls, wc);
    for (i = 0; i < calls && i < 8; i++) printf(" (%ld,%ld)->%ld", c_off[i], c_n[i], c_ret[i]);
    printf("\n");
}
int main(void) {
    long r; long x;
    x = 0 - 1;
    set(99999, 99999, 99999); r = fwrite_under_test(buf, 0, 5, stdout);
    check("sz0", r, 0, 0, x, x, x, x, x, x);
    set(99999, 99999, 99999); r = fwrite_under_test(buf, 4, 0, stdout);
    check("n0", r, 0, 0, x, x, x, x, x, x);
    set(99999, 99999, 99999); r = fwrite_under_test(buf, 4, 5, stdout);
    check("complete", r, 5, 1, 0, 20, 20, x, x, x);
    set(7, 99999, 99999); r = fwrite_under_test(buf, 4, 5, stdout);
    check("short_then_ok", r, 5, 2, 0, 20, 7, 7, 13, 13);
    set(7, 0 - 28, 99999); r = fwrite_under_test(buf, 4, 5, stdout);
    check("short_then_err", r, 1, 2, 0, 20, 7, 7, 13, 0 - 28);
    set(0, 99999, 99999); r = fwrite_under_test(buf, 4, 5, stdout);
    check("zero_stops", r, 0, 1, 0, 20, 0, x, x, x);
    set(9, 0, 99999); r = fwrite_under_test(buf, 4, 5, stdout);
    check("round_down", r, 2, 2, 0, 20, 9, 9, 11, 0);
    set(99999, 99999, 99999); r = fwrite_under_test(buf, 0x4000000000000000, 4, stdout);
    check("overflow", r, 0, 0, x, x, x, x, x, x);
    set(99999, 99999, 99999); r = fwrite_under_test(buf, 0 - 1, 4, stdout);
    check("negative_sz", r, 0, 0, x, x, x, x, x, x);
    set(99999, 99999, 99999); r = fwrite_under_test(buf, 4, 0 - 1, stdout);
    check("negative_n", r, 0, 0, x, x, x, x, x, x);
    set(500, 99999, 99999); r = fwrite_under_test(buf, 4, 5, stdout);
    check("over_answer", r, 0, 1, 0, 20, 500, x, x, x);
    printf("END fails=%d\n", fails);
    return fails;
}
C2
} > "$T/f.c"

bad=0
judge() {  # $1 = path name, $2 = output file, $3 = the probe's exit status
    # A pass needs BOTH the text (11 PASS, 0 FAIL, END fails=0) and exit 0:
    # a probe that prints every PASS and then exits 2, is killed by a signal
    # or by the watchdog (alarm -> 142) is a failure.  $3 is the status of
    # the command itself, saved right after it ran -- never a pipe's tail.
    sed 's/^/    /' "$2"
    p=$(grep -c '^PASS ' "$2"); f=$(grep -c '^FAIL ' "$2")
    if [ "$3" = 0 ] && [ "$p" = 11 ] && [ "$f" = 0 ] && grep -q '^END fails=0$' "$2"; then
        echo "  $1: SIMULATED 11/11 PASS (exit 0)"
    else echo "  $1: SIMULATED FAIL (pass $p, fail $f, exit $3)"; bad=1; fi
}
echo "== native (osx/arm64 executable)"
if b 30 "$UA" "$T/f.c" -b osx/arm64 -o "$T/x" >"$T/build.log" 2>&1; then
    b 20 "$T/x" > "$T/o1" 2>&1; rc=$?; judge native "$T/o1" $rc
else cat "$T/build.log"; echo "  native: FAIL build"; bad=1; fi
echo "== -run"
b 30 "$UA" -run "$T/f.c" > "$T/o2" 2>&1; rc=$?; judge -run "$T/o2" $rc
echo "== python --drive built"
(cd "$R" && b 55 python3 -m unisa run "$T/f.c" --drive built) > "$T/o3" 2>&1; rc=$?; judge python "$T/o3" $rc
[ $bad = 0 ] && echo "SIMULATED fwrite: all paths PASS" || echo "SIMULATED fwrite: FAIL"
exit $bad
